---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo
  namespace: nginx-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-demo
  template:
    metadata:
      labels:
        app: nginx-demo
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - nginx-demo
                topologyKey: kubernetes.io/hostname
      containers:
        - name: nginx
          image: nginx:1.27.2
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-demo-svc
  namespace: nginx-demo
spec:
  selector:
    app: nginx-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: nginx-demo-route
  namespace: nginx-demo
  annotations:
    link.argocd.argoproj.io/link: http://nginx-demo.talos.fritz.box
spec:
  parentRefs:
    - kind: Gateway
      name: nginx-gateway
      namespace: nginx-demo
  hostnames:
    - nginx-demo.talos.fritz.box
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: nginx-demo-svc
          port: 80
