---
# Based on the `argocd-server` from ArgoCD (as seen in the ArgoCD UI)
# This service is used to expose ArgoCD metrics on a NodePort.
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argo-cd
    app.kubernetes.io/name: argocd-server-metrics
    app.kubernetes.io/part-of: argocd
  name: argocd-server-metrics-svc
  namespace: argocd
spec:
  selector:
    app.kubernetes.io/name: argocd-server
  ports:
    - name: metrics
      port: 8083
      protocol: TCP
      targetPort: 8083
      nodePort: 30093
  type: NodePort
