---
# Based on the `argocd-repo-server` from ArgoCD (as seen in the ArgoCD UI)
# This service is used to expose ArgoCD metrics on a NodePort.
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: repo-server
    app.kubernetes.io/instance: argo-cd
    app.kubernetes.io/name: argocd-repo-server
    app.kubernetes.io/part-of: argocd
  name: argocd-repo-server-metrics-svc
  namespace: argocd
spec:
  selector:
    app.kubernetes.io/name: argocd-repo-server
  ports:
    - name: metrics
      port: 8084
      protocol: TCP
      targetPort: 8084
      nodePort: 30094
  type: NodePort
