---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-metrics-server
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring-logging
  ignoreDifferences:
    - group: argoproj.io
      jsonPointers:
        - /status
      kind: Application
  project: default
  source:
    path: charts/metrics-server
    repoURL: https://github.com/kubernetes-sigs/metrics-server.git
    targetRevision: v0.7.2
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - allowEmpty=true
      - CreateNamespace=true
