---
- name: Services  ----  Telemetry Metrics  ----  Create and start services
  community.docker.docker_compose_v2:
    project_src: "{{ services_stack_metrics }}"
    wait: true
    wait_timeout: 60 # seconds
  environment:
    HOSTNAME: "{{ ansible_hostname }}"
  register: output

- name: Services  ----  Telemetry Metrics  ----  Verify that services are running
  ansible.builtin.assert:
    that:
      - alloy_container.State == 'running'
      - node_exporter_container.State == 'running'
      - cadvisor_container.State == 'running'
  vars:
    ## Attribute `Services` refers to the name of the respective service in the docker-compose.yml file. So the
    ## they must match those defined in https://github.com/sommerfeld-io/telemetry/blob/main/components/metrics/docker-compose.yml.
    ## Attribute `State` refers to the current state of the container (e.g. running, exited, etc.).
    alloy_container: >-
      {{ output.containers | selectattr("Service", "equalto", "alloy") | first }}
    node_exporter_container: >-
      {{ output.containers | selectattr("Service", "equalto", "node_exporter") | first }}
    cadvisor_container: >-
      {{ output.containers | selectattr("Service", "equalto", "cadvisor") | first }}
