---
- name: Config  ----  Cron Job  ----  Ensure permissions
  ansible.builtin.file:
    path: "{{ item }}"
    mode: u=rwx,g=x,o=x # ubuntu default = rwxr-xr-x
  loop:
    - /etc/crontab
    - /etc/cron.hourly
    - /etc/cron.daily
    - /etc/cron.weekly
    - /etc/cron.monthly
    - /etc/cron.yearly
    - /etc/cron.d
