---
# See https://ansible.readthedocs.io/projects/lint/configuring
# https://ansible.readthedocs.io/projects/lint/profiles
profile: basic

var_naming_pattern: "^[a-z_][a-z0-9_]*$"

use_default_rules: false

exclude_paths:
  - components/ansible/roles/ansible-roles-collection
  ## Ignore the following due to ansible-vault usage in playbooks and vars files
  - components/ansible/vars/grafana-vault.yml
  - components/ansible/playbooks/grafana-agents.yml
  - components/ansible/playbooks/grafana-cloud.yml
  - components/ansible/playbooks/grafana.yml
  - components/ansible/playbooks/all.yml

enable_list:
  - no-log-password
  - no-same-owner
  - yaml

warn_list:
  - args
  - command-instead-of-module
  - empty-string-compare
  - latest[git]
  - name[missing]
  - no-changed-when
  - package-latest

skip_list:
  - yaml[line-length]
  - role-name[path]

offline: true
