---
extends: default

# Helm charts are excluded because they are validated with helm lint
ignore: |
  node_modules
  .vagrant
  target
  components/minikube
  components/talos-cluster/node-configs/generated

rules:
  line-length:
    max: 100
    allow-non-breakable-inline-mappings: true
    level: warning
  new-lines:
    type: unix
  braces:
    max-spaces-inside: 1
    level: error
  brackets:
    max-spaces-inside: 1
    level: error
  comments:
    min-spaces-from-content: 1
