---
site_name: Homelab Configs
site_url: https://www.sommerfeld.io
site_author: Sebastian Sommerfeld
site_description: >-
  Homelab Configs for sommerfeld.io projects.

repo_name: sommerfeld-io/configs-homelab
repo_url: https://github.com/sommerfeld-io/configs-homelab

copyright: >
  Copyright &copy; 2024 Sommerfeld.io |
  <a href="#__consent">Cookie settings</a>

docs_dir: docs
site_dir: target/docs/site

theme:
  name: material
  font:
    text: Work Sans
  palette:
    scheme: slate
    primary: blue grey # black
    accent: deep orange
  features:
    - content.code.copy
    - content.tabs.link
    # - navigation.tabs
    - navigation.footer
    - navigation.expand
    # - navigation.sections
    - navigation.tracking

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - kroki:
  - search:

extra:
  consent:
    title: Cookie consent
    description: >-
      Our documentation website is hosted on GitHub Pages and uses services from GitHub,
      Google Fonts, and Kroki, each with their own terms and privacy policies. We do not
      control or influence the data these third parties may collect. The site itself does
      not set cookies, track users, or collect personal data. For detals, see our
      <a href="https://github.com/sommerfeld-io/.github/blob/main/docs/terms.md">Terms of Use</a>.
    actions:
      - accept
      - reject
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sommerfeld-io/configs-homelab

nav:
  - Introduction: index.md
  - Ubuntu Workstations:
      - Setup Guide: nodes/ubuntu-workstations/index.md
  - Raspberry Pi Nodes:
      - Setup Guide: nodes/raspi/index.md
      - nodes/raspi/admin-pi.md
  - Ansible Playbooks:
      - Cleanup: ansible/cleanup.md
      - RasPi: ansible/raspi.md
      - Repositories: ansible/repositories.md
      - Telemetry: ansible/telemetry.md
      - Ubuntu Desktop: ansible/ubuntu-desktop.md
      - Ubuntu Desktop Steam: ansible/ubuntu-desktop-steam.md
  - Talos Cluster:
      - Overview: nodes/talos-cluster/index.md
      - Installation: nodes/talos-cluster/installation.md
      - nodes/talos-cluster/howto/interact.md
      - nodes/talos-cluster/howto/deploy-application-with-argocd.md
      - nodes/talos-cluster/howto/update-argocd.md
      - Telemetry: nodes/talos-cluster/telemetry.md
  - Api Docs:
      - Docker Stacks:
          - api-docs/docker-stacks/portainer.md
      - Apps in Talos:
          - api-docs/manifests/apps/hello-world-nginx.md
          - api-docs/manifests/apps/kroki.md
          - api-docs/manifests/apps/apache-demo.md
          - api-docs/manifests/apps/telemetry.md
          - api-docs/manifests/apps/nginx-demo.md
      - Helm Charts:
          - api-docs/helm-charts/hello-world-nginx.md
  - license.md
  - Releases on GitHub ⧉: https://github.com/sommerfeld-io/configs-homelab/releases
  - Architecture Decision Records on GitHub ⧉: https://github.com/sommerfeld-io/configs-homelab/issues?q=is%3Aissue+label%3AADR
  - Development Guide ⧉: https://github.com/sommerfeld-io/.github/blob/main/docs/development-guide.md
  - Other Code Guidelines ⧉: https://github.com/sommerfeld-io/.github/blob/main/.github/copilot-instructions.md
  - How to Contribute ⧉: https://github.com/sommerfeld-io/.github/blob/main/CONTRIBUTING.md
  - Code of Conduct ⧉: https://github.com/sommerfeld-io/.github/blob/main/CODE_OF_CONDUCT.md
  - Security Policy ⧉: https://github.com/sommerfeld-io/.github/blob/main/SECURITY.md
  - Terms of Use ⧉: https://github.com/sommerfeld-io/.github/blob/main/docs/terms.md
