---
site_name: Homelab Configs
site_url: https://www.sommerfeld.io
site_author: Sebastian Sommerfeld
site_description: >-
  Homelab Configs for sommerfeld.io projects.

repo_name: sommerfeld-io/configs-homelab
repo_url: https://github.com/sommerfeld-io/configs-homelab

copyright: Copyright &copy; 2024 Sommerfeld.io

docs_dir: docs
site_dir: target/docs/site

theme:
  name: material
  font:
    text: Work Sans
  palette:
    scheme: slate
    primary: black
    # # Palette toggle for light mode
    # - scheme: default
    #   primary: &header-color black
    #   accent: *header-color
    #   toggle:
    #     icon: material/brightness-7
    #     name: Switch to dark mode
    # # Palette toggle for dark mode
    # - scheme: slate
    #   primary: *header-color
    #   accent: *header-color
    #   toggle:
    #     icon: material/brightness-4
    #     name: Switch to light mode
  features:
    - content.code.copy
    - content.tabs.link
    - navigation.tabs
    # - navigation.footer
    # - navigation.sections
    # - navigation.expand
    - navigation.tracking

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - kroki:
      ServerURL: !ENV [KROKI_SERVER_URL, 'https://kroki.io']
  - search:

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sommerfeld-io/configs-homelab

nav:
  - Home:
      - index.md
      - memos.md
  - Workstations and RasPi Nodes:
      - nodes/ubuntu-workstations.md
      - Raspberry Pi:
          - nodes/raspi-pihole-fritz-box.md
      - nodes/talos/index.md
  - Api Docs:
      - Docker:
          - api-docs/docker/ops-docker-compose-yml.md
          - api-docs/docker/portainer-docker-compose-yml.md
      - Scripts:
          - api-docs/scripts/ansible-cli.md
          - api-docs/scripts/docker-stacks.md
          - api-docs/scripts/minikube-cli.md
  - About this Project:
      - about/development-guide.md
      - about/contribute.md
      - about/security.md
      - about/code-of-conduct.md
      - about/license.md
      - about/terms.md
