---
version: '3.42.1'

dotenv: ['.env']

vars:
  INSPEC_DIR: tests/inspec
  REPO: https://raw.githubusercontent.com/sommerfeld-io/.github

includes:
  common: https://raw.githubusercontent.com/sommerfeld-io/.github/refs/heads/main/assets/task/common.yml
  copilot: .github/skills/taskfile.yml

tasks:

  update:
    desc: Update project dependencies and submodules
    cmds:
      - git submodule update --remote

  cleanup:filesystem:
    desc: Cleanup the filesystem for this project
    cmds:
      - rm -rf .cache
      - sudo rm -rf .ansible
      - sudo rm -rf .devcontainer/ops
      - rm -rf node_modules
      - rm -rf target
      - for: &inspec-profiles ['admin-pi', 'ansible-baseline', 'picon', 'raspi-baseline', 'runner-04-pi']
        cmd: |
          sudo rm -rf tests/inspec/{{ .ITEM }}/vendor
          sudo rm -rf tests/inspec/{{ .ITEM }}/inspec.lock
      - find . -type f -exec chmod ugo+r {} +
      - find . -type d -exec chmod 755 {} +
      - find . -name "*.sh" -type f -exec chmod +x {} +
      - task: update

  cleanup:
    desc: Cleanup the development environment for this project
    cmds:
      - docker compose down --remove-orphans
      - docker container prune -f
      - docker volume prune -f
      - task: cleanup:filesystem

  # ===============================================================================================

  lint:
    desc: Run all project linters (except Dockerfile linters)
    cmds:
      - task: cleanup:filesystem
      - for: ['yaml', 'workflows', 'filenames', 'folders', 'ansible', 'alloy-config'] # , 'markdown-links'
        cmd: docker compose up lint-{{ .ITEM }} --exit-code-from lint-{{ .ITEM }}

  # ===============================================================================================

  copilot:lint-and-fix:
    desc: 'Use GitHub Copilot to lint and fix issues in the project'
    cmds:
      - task: cleanup
      - copilot --allow-all --prompt "/lint-and-fix"

  copilot:pull-request:
    desc: 'Use GitHub Copilot to create or update a pull request with a summary of all changes based on commit messages'
    cmds:
      - task: update
      - copilot --allow-all --prompt "/create-or-update-pull-request"

  # ===============================================================================================

  docs:generate:
    desc: 'Generate Markdown files for documentation'
    vars:
      GRAFANA_CLOUD_DOCS: docs/ansible/roles/grafana-cloud
      GRAFANA_CLOUD_SRC: ansible/roles/grafana-cloud
    cmds:
      - echo "Collecting documentation from other Markdown files ..."
      - task: common:copy
        vars: { SRC: docs/index.md, DEST: README.md }
      - task: common:copy
        vars: { SRC: docs/license.md, DEST: LICENSE.md }
      - mkdir -p {{ .GRAFANA_CLOUD_DOCS }}
      - task: common:copy
        vars: { SRC: "{{ .GRAFANA_CLOUD_SRC }}/alloy/README.md", DEST: "{{ .GRAFANA_CLOUD_DOCS }}/alloy.md" }
      - task: common:copy
        vars: { SRC: "{{ .GRAFANA_CLOUD_SRC }}/dashboards/README.md", DEST: "{{ .GRAFANA_CLOUD_DOCS }}/dashboards.md" }

  docs:run:
    desc: Run the documentation server
    cmds:
      - task: docs:generate
      - docker compose up docs-dev-server

  # ===============================================================================================

  ansible:cleanup:
    vars:
      PLAYBOOK: cleanup.yml
    desc: &ansible-desc HOST ONLY | Run Ansible playbook | {{ .PLAYBOOK }}
    dir: &ansible-dir ansible
    cmds: &ansible-cmd
      - git submodule update --remote
      - ansible-playbook "playbooks/{{ .PLAYBOOK }}" --inventory hosts.yml --ask-become-pass --ask-vault-pass

  ansible:all:
    vars:
      PLAYBOOK: all.yml
    desc: *ansible-desc
    dir: *ansible-dir
    cmds: *ansible-cmd

  ansible:desktop:
    vars:
      PLAYBOOK: desktop.yml
    desc: *ansible-desc
    dir: *ansible-dir
    cmds: *ansible-cmd

  ansible:desktop:steam:
    vars:
      PLAYBOOK: desktop-steam.yml
    desc: *ansible-desc
    dir: *ansible-dir
    cmds: *ansible-cmd

  ansible:grafana:
    vars:
      PLAYBOOK: grafana.yml
    desc: *ansible-desc
    dir: *ansible-dir
    cmds: *ansible-cmd

  ansible:grafana:agents:
    vars:
      PLAYBOOK: grafana-agents.yml
    desc: *ansible-desc
    dir: *ansible-dir
    cmds: *ansible-cmd

  ansible:grafana:cloud:
    vars:
      PLAYBOOK: grafana-cloud.yml
    desc: *ansible-desc
    dir: *ansible-dir
    cmds: *ansible-cmd

  ansible:ollama:
    vars:
      PLAYBOOK: ollama.yml
    desc: *ansible-desc
    dir: *ansible-dir
    cmds: *ansible-cmd

  ansible:ping:
    vars:
      PLAYBOOK: ping.yml
    desc: *ansible-desc
    dir: *ansible-dir
    cmds: *ansible-cmd

  ansible:raspi:
    vars:
      PLAYBOOK: raspi.yml
    desc: *ansible-desc
    dir: *ansible-dir
    cmds: *ansible-cmd

  ansible:repositories:
    vars:
      PLAYBOOK: repositories.yml
    desc: *ansible-desc
    dir: *ansible-dir
    cmds: *ansible-cmd

  ansible:scan:
    vars:
      PLAYBOOK: scan.yml
    desc: *ansible-desc
    dir: *ansible-dir
    cmds: *ansible-cmd

  ansible:vault:
    vars:
      VAULT_FILE: ansible/vars/vault.yml
    desc: &ansible-vault-desc Show and edit the contents of the Ansible Vault file
    cmds: &ansible-vault-cmd
      - ansible-vault edit {{ .VAULT_FILE }}

  ansible:vault:grafana:
    vars:
      VAULT_FILE: ansible/vars/grafana-vault.yml
    desc: *ansible-vault-desc
    cmds: *ansible-vault-cmd

  # ===============================================================================================

  inspec:check:
    desc: &inspec-check-desc Vendor and check InSpec profile validity
    cmds:
      - for: *inspec-profiles
        task: inspec:check:{{ .ITEM }}

  inspec:check:*:
    desc: *inspec-check-desc
    vars:
      PROFILE: '{{ index .MATCH 0 }}'
    cmds:
      - rm -f "{{ .INSPEC_DIR }}/{{ .PROFILE }}/inspec.lock"
      - docker compose run --rm inspec vendor "{{ .INSPEC_DIR }}/{{ .PROFILE }}" --overwrite --chef-license=accept
      - docker compose run --rm inspec check "{{ .INSPEC_DIR }}/{{ .PROFILE }}" --chef-license=accept

  internal:inspec:run-profile:
    desc: 'Run the profile'
    internal: true
    vars:
      USER: sebastian
    cmds:
      - docker compose run --rm --env SSH_AUTH_SOCK=/ssh-auth.sock -v "$SSH_AUTH_SOCK:/ssh-auth.sock" inspec exec "{{ .INSPEC_DIR }}/{{ .PROFILE }}" --target "ssh://{{ .USER }}@{{ .HOST }}" --no-distinct-exit --chef-license=accept # --no-color

  inspec:run:caprica:
    desc: HOST ONLY | Run InSpec against {{ .HOST }}
    vars:
      HOST: caprica.fritz.box
    cmds:
      - for: ['ansible-baseline']
        task: internal:inspec:run-profile
        vars:
          HOST: '{{ .HOST }}'
          PROFILE: '{{ .ITEM }}'

  inspec:run:kobol:
    desc: HOST ONLY | Run InSpec against {{ .HOST }}
    vars:
      HOST: kobol.fritz.box
    cmds:
      - for: ['ansible-baseline']
        task: internal:inspec:run-profile
        vars:
          HOST: '{{ .HOST }}'
          PROFILE: '{{ .ITEM }}'

  inspec:run:picon:
    desc: HOST ONLY | Run InSpec against {{ .HOST }}
    vars:
      HOST: picon.fritz.box
    cmds:
      - for: ['ansible-baseline', 'picon']
        task: internal:inspec:run-profile
        vars:
          HOST: '{{ .HOST }}'
          PROFILE: '{{ .ITEM }}'

  inspec:run:admin-pi:
    desc: HOST ONLY | Run InSpec against {{ .HOST }}
    vars:
      HOST: admin-pi.fritz.box
    cmds:
      - for: ['raspi-baseline', 'admin-pi']
        task: internal:inspec:run-profile
        vars:
          HOST: '{{ .HOST }}'
          PROFILE: '{{ .ITEM }}'

  inspec:run:runner-04-pi:
    desc: HOST ONLY | Run InSpec against {{ .HOST }}
    vars:
      HOST: runner-04-pi.fritz.box
    cmds:
      - for: ['raspi-baseline', 'runner-04-pi']
        task: internal:inspec:run-profile
        vars:
          HOST: '{{ .HOST }}'
          PROFILE: '{{ .ITEM }}'

  inspec:run:runner-05-pi:
    desc: HOST ONLY | Run InSpec against {{ .HOST }}
    vars:
      HOST: runner-05-pi.fritz.box
    cmds:
      - for: ['raspi-baseline']
        task: internal:inspec:run-profile
        vars:
          HOST: '{{ .HOST }}'
          PROFILE: '{{ .ITEM }}'

  inspec:run:runner-06-pi5:
    desc: HOST ONLY | Run InSpec against {{ .HOST }}
    vars:
      HOST: runner-06-pi5.fritz.box
    cmds:
      - for: ['raspi-baseline']
        task: internal:inspec:run-profile
        vars:
          HOST: '{{ .HOST }}'
          PROFILE: '{{ .ITEM }}'
