---
version: '3.42.1'

vars:
  INSPEC_IMAGE: chef/inspec:5.22.76
  INSPEC_PROFILES: ['ansible-baseline']

tasks:

  cleanup:
    desc: 'Cleanup the environment'
    cmds:
      - docker compose up cleanup
      - docker compose down --remove-orphans

  # ===============================================================================================

  lint:
    desc: 'Run all project linters outside of Dockerfile linters'
    cmds:
      - for:
          matrix:
            LINTER: ['yaml', 'workflows', 'filenames', 'folders', 'markdown-links', 'ansible', 'helm', 'k8s-manifests']
        cmd: docker compose up lint-{{.ITEM.LINTER}} --exit-code-from lint-{{.ITEM.LINTER}}

  # ===============================================================================================

  docs:run:
    desc: 'Run the documentation server'
    cmds:
      - docker compose up docs-dev-server

  # ===============================================================================================

  host:conky:
    desc: 'HOST ONLY | (Re-)start conky'
    dir: components/conky
    cmds:
      - killall conky || true
      - ./run.sh

  # ===============================================================================================

  host:test:inspec:run:
    desc: 'HOST ONLY | Run InSpec against all nodes'
    dir: &inspec-dir tests/inspec
    deps:
      - task: host:test:inspec:check
    cmds:
      - for: ['caprica.fritz.box', 'kobol.fritz.box']
        task: host:test:inspec:run:{{.ITEM}}

  host:test:inspec:check:
    desc: 'HOST ONLY | Check InSpec profile validity'
    dir: *inspec-dir
    cmds:
      - for:
          var: INSPEC_PROFILES
        cmd: |
          docker run --rm \
            --volume "$(pwd):$(pwd)" \
            --workdir "$(pwd)" \
            "{{.INSPEC_IMAGE}}" check "{{.ITEM}}" --chef-license=accept

  host:test:inspec:run:*:
    desc: 'HOST ONLY | Run InSpec against single node | (* = FQDN)'
    dir: *inspec-dir
    vars:
      HOST: '{{index .MATCH 0}}'
      USER: sebastian
    cmds:
      - for:
          var: INSPEC_PROFILES
        cmd: |
          docker run --rm \
            --env SSH_AUTH_SOCK=/ssh-auth.sock \
            --volume "$SSH_AUTH_SOCK:/ssh-auth.sock" \
            --volume "$(pwd):$(pwd)" \
            --workdir "$(pwd)" \
            "{{.INSPEC_IMAGE}}" exec "{{.ITEM}}" --target "ssh://{{.USER}}@{{.HOST}}" --chef-license=accept

  # ===============================================================================================

  host:virtual-talos-admin:start:
    desc: 'HOST ONLY | Startup the Talos Administration Vagrantbox'
    dir: &talos-vm-dir components/talos-cluster/virtual-talos-admin
    cmds:
      - vagrant validate
      - vagrant up
      - vagrant ssh

  host:virtual-talos-admin:stop:
    desc: 'HOST ONLY | Shutdown the Talos Administration Vagrantbox'
    dir: *talos-vm-dir
    cmds: &talos-vm-stop
      - vagrant halt

  host:virtual-talos-admin:remove:
    desc: 'HOST ONLY | Remove the Talos Administration Vagrantbox'
    dir: *talos-vm-dir
    cmds:
      - vagrant halt
      - vagrant destroy --force
