---
version: '3.42.1'

dotenv: ['.env']

vars:
  INSPEC_DIR: tests/inspec
  REPO: https://raw.githubusercontent.com/sommerfeld-io/.github

includes:
  common: https://raw.githubusercontent.com/sommerfeld-io/.github/refs/heads/main/assets/task/common.yml

tasks:

  sync:assets-from-github:
    desc: 'Sync assets from the central sommerfeldio/.github repository'
    cmds:
      - echo "Syncing assets from the central sommerfeldio/.github repository..."
      - task: common:download
        vars: { DEST: ".github/copilot-instructions.md", URL: "{{ .REPO }}/refs/heads/main/.github/copilot-instructions.md" }
      - task: common:download
        vars: { DEST: ".vscode/settings.json", URL: "{{ .REPO }}/refs/heads/main/.vscode/settings.json" }
      - task: common:download
        vars: { DEST: ".github/workflows/codeql.yml", URL: "{{ .REPO }}/refs/heads/main/.github/workflows/codeql.yml" }
      - task: common:download
        vars: { DEST: ".github/workflows/housekeeping-issues.yml", URL: "{{ .REPO }}/refs/heads/main/.github/workflows/housekeeping-issues.yml" }
      - task: common:download
        vars: { DEST: ".github/workflows/housekeeping-labels.yml", URL: "{{ .REPO }}/refs/heads/main/.github/workflows/housekeeping-labels.yml" }

  # ===============================================================================================

  cleanup:
    desc: Cleanup the development environment for this project
    cmds:
      - docker compose down --remove-orphans
      - rm -rf .cache
      - sudo rm -rf .ansible
      - sudo rm -rf .devcontainer/ops
      - rm -rf node_modules
      - rm -rf target
      - for: &inspec-profiles ['ansible-baseline', 'raspi-baseline', 'admin-pi', 'talos-baseline']
        cmd: |
          sudo rm -rf tests/inspec/{{ .ITEM }}/vendor
          sudo rm -rf tests/inspec/{{ .ITEM }}/inspec.lock
      - find . -type f -exec chmod ugo+r {} +
      - find . -type d -exec chmod 755 {} +
      - find . -name "*.sh" -type f -exec chmod +x {} +
      - git pull --recurse-submodules

  # ===============================================================================================

  lint:
    desc: Run all project linters (except Dockerfile linters)
    cmds:
      - for: ['yaml', 'workflows', 'filenames', 'folders', 'ansible', 'helm', 'k8s-manifests', 'markdown-links']
        cmd: docker compose up lint-{{ .ITEM }} --exit-code-from lint-{{ .ITEM }}

  # ===============================================================================================

  internal:docs:generate:from-readme:
    desc: 'Collecting documentation README.md files in this repo'
    internal: true
    vars:
      FOLDERS:
        sh: find {{ .BASEPATH }} -maxdepth 1 -type d -not -path '{{ .BASEPATH }}' -exec basename {} \;
    cmds:
      - rm -rf docs/{{ .TARGET_PATH }}
      - mkdir -p docs/{{ .TARGET_PATH }}
      - echo "Contents of this folder are auto-generated" > docs/{{ .TARGET_PATH }}/.auto-generated
      - for: { var: FOLDERS }
        task: common:copy
        vars: { SRC: "{{ .BASEPATH }}/{{ .ITEM }}/README.md", DEST: "docs/{{ .TARGET_PATH }}/{{ .ITEM }}.md" }
    generates:
      - "docs/{{ .TARGET_PATH }}/{{ .ITEM }}.md"

  docs:generate:
    desc: 'Generate Markdown files for documentation'
    cmds:
      - echo "Collecting documentation from other Markdown files ..."
      - task: common:copy
        vars: { SRC: docs/index.md, DEST: README.md }
      - task: common:copy
        vars: { SRC: docs/license.md, DEST: LICENSE.md }
      - task: internal:docs:generate:from-readme
        vars: { BASEPATH: components/talos-cluster/manifests/apps, TARGET_PATH: api-docs/manifests/apps }
      - task: internal:docs:generate:from-readme
        vars: { BASEPATH: components/talos-cluster/helm-charts, TARGET_PATH: api-docs/helm-charts }

  docs:run:
    desc: Run the documentation server
    cmds:
      - task: docs:generate
      - docker compose up docs-dev-server

  # ===============================================================================================

  ansible:cleanup:
    vars:
      PLAYBOOK: cleanup.yml
    desc: &ansible-desc HOST ONLY | Run Ansible playbook | {{ .PLAYBOOK }}
    dir: &ansible-dir components/ansible
    preconditions: &allowed-hosts
      - sh: '[ "$(hostname)" = "kobol" ] || [ "$(hostname)" = "caprica" ] || [ "$(hostname)" = "admin-pi" ]'
        msg: "[ERROR] This task can only be run on host 'kobol' or 'caprica'."
    cmds: &ansible-cmd
      - ansible-playbook "playbooks/{{ .PLAYBOOK }}" --inventory hosts.yml --ask-become-pass

  ansible:raspi:
    vars:
      PLAYBOOK: raspi.yml
    desc: *ansible-desc
    dir: *ansible-dir
    preconditions: *allowed-hosts
    cmds: *ansible-cmd

  ansible:ubuntu:desktop:
    vars:
      PLAYBOOK: ubuntu-desktop.yml
    desc: *ansible-desc
    dir: *ansible-dir
    preconditions: *allowed-hosts
    cmds: *ansible-cmd

  ansible:ubuntu:desktop:steam:
    vars:
      PLAYBOOK: ubuntu-desktop-steam.yml
    desc: *ansible-desc
    dir: *ansible-dir
    preconditions: *allowed-hosts
    cmds: *ansible-cmd

  ansible:repositories:
    vars:
      PLAYBOOK: repositories.yml
    desc: *ansible-desc
    dir: *ansible-dir
    preconditions: *allowed-hosts
    cmds: *ansible-cmd

  ansible:telemetry:
    vars:
      PLAYBOOK: telemetry.yml
    desc: *ansible-desc
    dir: *ansible-dir
    preconditions: *allowed-hosts
    cmds: *ansible-cmd

  ansible:telemetry:exporters:
    vars:
      PLAYBOOK: telemetry-exporters.yml
    desc: *ansible-desc
    dir: *ansible-dir
    preconditions: *allowed-hosts
    cmds: *ansible-cmd

  # ===============================================================================================

  inspec:check:
    desc: &inspec-check-desc Vendor and check InSpec profile validity
    cmds:
      - for: *inspec-profiles
        task: inspec:check:{{ .ITEM }}

  inspec:check:*:
    desc: *inspec-check-desc
    vars:
      PROFILE: '{{ index .MATCH 0 }}'
    cmds:
      - rm -f "{{ .INSPEC_DIR }}/{{ .PROFILE }}/inspec.lock"
      - docker compose run --rm inspec vendor "{{ .INSPEC_DIR }}/{{ .PROFILE }}" --overwrite --chef-license=accept
      - docker compose run --rm inspec check "{{ .INSPEC_DIR }}/{{ .PROFILE }}" --chef-license=accept

  internal:inspec:run-profile:
    desc: 'Run the profile'
    internal: true
    vars:
      USER: sebastian
    cmds:
      - docker compose run --rm --env SSH_AUTH_SOCK=/ssh-auth.sock -v "$SSH_AUTH_SOCK:/ssh-auth.sock" inspec exec "{{ .INSPEC_DIR }}/{{ .PROFILE }}" --target "ssh://{{ .USER }}@{{ .HOST }}" --no-distinct-exit --chef-license=accept # --no-color

  inspec:run:caprica:
    desc: HOST ONLY | Run InSpec against {{ .HOST }}
    vars:
      HOST: caprica.fritz.box
    preconditions: *allowed-hosts
    cmds:
      - for: ['ansible-baseline']
        task: internal:inspec:run-profile
        vars:
          HOST: '{{ .HOST }}'
          PROFILE: '{{ .ITEM }}'

  inspec:run:kobol:
    desc: HOST ONLY | Run InSpec against {{ .HOST }}
    vars:
      HOST: kobol.fritz.box
    preconditions: *allowed-hosts
    cmds:
      - for: ['ansible-baseline']
        task: internal:inspec:run-profile
        vars:
          HOST: '{{ .HOST }}'
          PROFILE: '{{ .ITEM }}'

  inspec:run:admin-pi:
    desc: HOST ONLY | Run InSpec against {{ .HOST }}
    vars:
      HOST: admin-pi.fritz.box
    preconditions: *allowed-hosts
    cmds:
      - for: ['raspi-baseline', 'admin-pi']
        task: internal:inspec:run-profile
        vars:
          HOST: '{{ .HOST }}'
          PROFILE: '{{ .ITEM }}'

  inspec:run:runner-04-pi:
    desc: HOST ONLY | Run InSpec against {{ .HOST }}
    vars:
      HOST: runner-04-pi.fritz.box
    preconditions: *allowed-hosts
    cmds:
      - for: ['raspi-baseline', 'runner-04-pi']
        task: internal:inspec:run-profile
        vars:
          HOST: '{{ .HOST }}'
          PROFILE: '{{ .ITEM }}'

  inspec:run:runner-05-pi:
    desc: HOST ONLY | Run InSpec against {{ .HOST }}
    vars:
      HOST: runner-05-pi.fritz.box
    preconditions: *allowed-hosts
    cmds:
      - for: ['raspi-baseline']
        task: internal:inspec:run-profile
        vars:
          HOST: '{{ .HOST }}'
          PROFILE: '{{ .ITEM }}'

  inspec:run:runner-06-pi5:
    desc: HOST ONLY | Run InSpec against {{ .HOST }}
    vars:
      HOST: runner-06-pi5.fritz.box
    preconditions: *allowed-hosts
    cmds:
      - for: ['raspi-baseline']
        task: internal:inspec:run-profile
        vars:
          HOST: '{{ .HOST }}'
          PROFILE: '{{ .ITEM }}'

  inspec:run:talos:
    desc: HOST ONLY | Run InSpec against Talos cluster
    vars:
      PROFILE: talos-baseline
    preconditions: *allowed-hosts
    cmds:
      - docker compose run --rm inspec exec "{{ .INSPEC_DIR }}/{{ .PROFILE }}" --no-distinct-exit --chef-license=accept

  # ===============================================================================================

  virtual-talos-admin:start:
    desc: HOST ONLY | Startup the Talos Administration Vagrantbox'
    dir: &talos-vm-dir components/talos-cluster/virtual-talos-admin
    preconditions: *allowed-hosts
    cmds:
      - vagrant validate
      - vagrant up

  virtual-talos-admin:stop:
    desc: HOST ONLY | Shutdown the Talos Administration Vagrantbox
    dir: *talos-vm-dir
    preconditions: *allowed-hosts
    cmds:
      - vagrant halt

  virtual-talos-admin:ssh:
    desc: HOST ONLY | SSH into the Talos Administration Vagrantbox
    dir: *talos-vm-dir
    preconditions: *allowed-hosts
    cmds:
      - vagrant ssh

  virtual-talos-admin:remove:
    desc: HOST ONLY | Remove the Talos Administration Vagrantbox
    dir: *talos-vm-dir
    preconditions: *allowed-hosts
    cmds:
      - vagrant halt
      - vagrant destroy --force
