---
version: '3.42.1'

dotenv: ['.env']

vars:
  INSPEC_DIR: tests/inspec
  REPO: https://raw.githubusercontent.com/sommerfeld-io/.github

includes:
  common: https://raw.githubusercontent.com/sommerfeld-io/.github/refs/heads/main/assets/task/common.yml

tasks:

  update:
    desc: Update project dependencies and submodules
    cmds:
      - git submodule update --remote

  cleanup:
    desc: Cleanup the development environment for this project
    cmds:
      - docker compose down --remove-orphans
      - docker container prune -f
      - docker volume prune -f
      - rm -rf .cache
      - sudo rm -rf .ansible
      - sudo rm -rf .devcontainer/ops
      - rm -rf node_modules
      - rm -rf target
      - for: &inspec-profiles ['admin-pi', 'ansible-baseline', 'raspi-baseline', 'runner-04-pi', 'talos-baseline']
        cmd: |
          sudo rm -rf tests/inspec/{{ .ITEM }}/vendor
          sudo rm -rf tests/inspec/{{ .ITEM }}/inspec.lock
      - find . -type f -exec chmod ugo+r {} +
      - find . -type d -exec chmod 755 {} +
      - find . -name "*.sh" -type f -exec chmod +x {} +
      - task: update

  # ===============================================================================================

  lint:
    desc: Run all project linters (except Dockerfile linters)
    cmds:
      - for: ['yaml', 'workflows', 'filenames', 'folders', 'ansible', 'markdown-links', 'alloy-config']
        cmd: docker compose up lint-{{ .ITEM }} --exit-code-from lint-{{ .ITEM }}

  # ===============================================================================================

  docs:generate:
    desc: 'Generate Markdown files for documentation'
    cmds:
      - echo "Collecting documentation from other Markdown files ..."
      - task: common:copy
        vars: { SRC: docs/index.md, DEST: README.md }
      - task: common:copy
        vars: { SRC: docs/license.md, DEST: LICENSE.md }

  docs:run:
    desc: Run the documentation server
    cmds:
      - task: docs:generate
      - docker compose up docs-dev-server

  # ===============================================================================================

  ansible:cleanup:
    vars:
      PLAYBOOK: cleanup.yml
    desc: &ansible-desc HOST ONLY | Run Ansible playbook | {{ .PLAYBOOK }}
    dir: &ansible-dir components/ansible
    cmds: &ansible-cmd
      - git submodule update --remote
      - ansible-playbook "playbooks/{{ .PLAYBOOK }}" --inventory hosts.yml --ask-become-pass --ask-vault-pass

  ansible:raspi:
    vars:
      PLAYBOOK: raspi.yml
    desc: *ansible-desc
    dir: *ansible-dir
    cmds: *ansible-cmd

  ansible:desktop:
    vars:
      PLAYBOOK: desktop.yml
    desc: *ansible-desc
    dir: *ansible-dir
    cmds: *ansible-cmd

  ansible:desktop:steam:
    vars:
      PLAYBOOK: desktop-steam.yml
    desc: *ansible-desc
    dir: *ansible-dir
    cmds: *ansible-cmd

  ansible:repositories:
    vars:
      PLAYBOOK: repositories.yml
    desc: *ansible-desc
    dir: *ansible-dir
    cmds: *ansible-cmd

  ansible:telemetry:
    vars:
      PLAYBOOK: telemetry.yml
    desc: *ansible-desc
    dir: *ansible-dir
    cmds: *ansible-cmd

  ansible:telemetry:exporters:
    vars:
      PLAYBOOK: telemetry-exporters.yml
    desc: *ansible-desc
    dir: *ansible-dir
    cmds: *ansible-cmd

  ansible:grafana-cloud:
    vars:
      PLAYBOOK: grafana-cloud.yml
    desc: *ansible-desc
    dir: *ansible-dir
    cmds: *ansible-cmd

  ansible:grafana-cloud:vault:
    vars: &grafana-cloud-vars
      VAULT_FILE: components/ansible/vars/grafana-cloud-vault.yml
    desc: Show and edit the contents of the Ansible Vault file for Grafana Cloud
    cmds:
      - ansible-vault edit {{ .VAULT_FILE }}

  # ===============================================================================================

  inspec:check:
    desc: &inspec-check-desc Vendor and check InSpec profile validity
    cmds:
      - for: *inspec-profiles
        task: inspec:check:{{ .ITEM }}

  inspec:check:*:
    desc: *inspec-check-desc
    vars:
      PROFILE: '{{ index .MATCH 0 }}'
    cmds:
      - rm -f "{{ .INSPEC_DIR }}/{{ .PROFILE }}/inspec.lock"
      - docker compose run --rm inspec vendor "{{ .INSPEC_DIR }}/{{ .PROFILE }}" --overwrite --chef-license=accept
      - docker compose run --rm inspec check "{{ .INSPEC_DIR }}/{{ .PROFILE }}" --chef-license=accept

  internal:inspec:run-profile:
    desc: 'Run the profile'
    internal: true
    vars:
      USER: sebastian
    cmds:
      - docker compose run --rm --env SSH_AUTH_SOCK=/ssh-auth.sock -v "$SSH_AUTH_SOCK:/ssh-auth.sock" inspec exec "{{ .INSPEC_DIR }}/{{ .PROFILE }}" --target "ssh://{{ .USER }}@{{ .HOST }}" --no-distinct-exit --chef-license=accept # --no-color

  inspec:run:caprica:
    desc: HOST ONLY | Run InSpec against {{ .HOST }}
    vars:
      HOST: caprica.fritz.box
    cmds:
      - for: ['ansible-baseline']
        task: internal:inspec:run-profile
        vars:
          HOST: '{{ .HOST }}'
          PROFILE: '{{ .ITEM }}'

  inspec:run:kobol:
    desc: HOST ONLY | Run InSpec against {{ .HOST }}
    vars:
      HOST: kobol.fritz.box
    cmds:
      - for: ['ansible-baseline']
        task: internal:inspec:run-profile
        vars:
          HOST: '{{ .HOST }}'
          PROFILE: '{{ .ITEM }}'

  inspec:run:picon:
    desc: HOST ONLY | Run InSpec against {{ .HOST }}
    vars:
      HOST: picon.fritz.box
    cmds:
      - for: ['ansible-baseline']
        task: internal:inspec:run-profile
        vars:
          HOST: '{{ .HOST }}'
          PROFILE: '{{ .ITEM }}'

  inspec:run:admin-pi:
    desc: HOST ONLY | Run InSpec against {{ .HOST }}
    vars:
      HOST: admin-pi.fritz.box
    cmds:
      - for: ['raspi-baseline', 'admin-pi']
        task: internal:inspec:run-profile
        vars:
          HOST: '{{ .HOST }}'
          PROFILE: '{{ .ITEM }}'

  inspec:run:runner-04-pi:
    desc: HOST ONLY | Run InSpec against {{ .HOST }}
    vars:
      HOST: runner-04-pi.fritz.box
    cmds:
      - for: ['raspi-baseline', 'runner-04-pi']
        task: internal:inspec:run-profile
        vars:
          HOST: '{{ .HOST }}'
          PROFILE: '{{ .ITEM }}'

  inspec:run:runner-05-pi:
    desc: HOST ONLY | Run InSpec against {{ .HOST }}
    vars:
      HOST: runner-05-pi.fritz.box
    cmds:
      - for: ['raspi-baseline']
        task: internal:inspec:run-profile
        vars:
          HOST: '{{ .HOST }}'
          PROFILE: '{{ .ITEM }}'

  inspec:run:runner-06-pi5:
    desc: HOST ONLY | Run InSpec against {{ .HOST }}
    vars:
      HOST: runner-06-pi5.fritz.box
    cmds:
      - for: ['raspi-baseline']
        task: internal:inspec:run-profile
        vars:
          HOST: '{{ .HOST }}'
          PROFILE: '{{ .ITEM }}'

  inspec:run:talos:
    desc: HOST ONLY | Run InSpec against Talos cluster
    vars:
      PROFILE: talos-baseline
    cmds:
      - docker compose run --rm inspec exec "{{ .INSPEC_DIR }}/{{ .PROFILE }}" --no-distinct-exit --chef-license=accept

  # ===============================================================================================

  virtual-talos-admin:start:
    desc: HOST ONLY | Startup the Talos Administration Vagrantbox'
    dir: &talos-vm-dir components/talos-cluster/virtual-talos-admin
    cmds:
      - vagrant validate
      - vagrant up

  virtual-talos-admin:stop:
    desc: HOST ONLY | Shutdown the Talos Administration Vagrantbox
    dir: *talos-vm-dir
    cmds:
      - vagrant halt

  virtual-talos-admin:ssh:
    desc: HOST ONLY | SSH into the Talos Administration Vagrantbox
    dir: *talos-vm-dir
    cmds:
      - vagrant ssh

  virtual-talos-admin:remove:
    desc: HOST ONLY | Remove the Talos Administration Vagrantbox
    dir: *talos-vm-dir
    cmds:
      - vagrant halt
      - vagrant destroy --force
