---
- name: Virtualization  ----  Vagrant
  block:

    - name: Virtualization  ----  Vagrant ---- Download and convert HashiCorp GPG key
      ansible.builtin.shell: |
        curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /etc/apt/keyrings/hashicorp-archive-keyring.gpg
      args:
        creates: /etc/apt/keyrings/hashicorp-archive-keyring.gpg

    - name: Virtualization  ----  Vagrant ---- Add apt repository (OS-codename {{ codename }})
      ansible.builtin.apt_repository:
        repo: "deb https://apt.releases.hashicorp.com {{ codename }} main"
        filename: hashicorp
        state: present
      vars:
        codename: "{{ ansible_distribution_release }}"
        # codename: noble # HashiCorp supports only LTS releases - so dynamically setting the distribution release might not work

    - name: Virtualization  ----  Vagrant ---- Install Vagrant packages
      ansible.builtin.apt:
        pkg:
          - vagrant
        state: latest
        update_cache: true

    - name: Virtualization  ----  Vagrant ---- Install Vagrant plugins
      ansible.builtin.shell: |
        vagrant plugin install vagrant-cachier
        # vagrant plugin install vagrant-vbguest
        # vagrant plugin install vagrant-docker-compose
      become: true
      become_user: "{{ ansible_user }}"
      args:
        executable: /bin/bash

    - name: Virtualization  ----  Vagrant ---- Verify installation
      ansible.builtin.command: vagrant --version
      register: virtualization_vagrant_version_output
      changed_when: false

    - name: Virtualization  ----  Vagrant ---- Print version
      ansible.builtin.debug:
        msg: "{{ virtualization_vagrant_version_output.stdout }}"
