---
common_omarchy_hardening_login_defs:
  - { key: PASS_MAX_DAYS, value: '99999' }
  - { key: PASS_MIN_DAYS, value: '0' }
  - { key: PASS_WARN_AGE, value: '7' }
  - { key: ENV_SUPATH, value: 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin' }
  - { key: ENV_PATH, value: 'PATH=/usr/local/bin:/usr/bin:/bin' }

common_omarchy_hardening_hardened_mountpoints:
  - /boot
  - /home
  - /var/log
