version: v1alpha1
debug: false
persist: true
machine:
    type: controlplane
    token: xda7de.yc5zihniea7b8juu
    ca:
        crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJQakNCOGFBREFnRUNBaEEvTldoVDhnQmw2czVhZk9RdTh3KzlNQVVHQXl0bGNEQVFNUTR3REFZRFZRUUsKRXdWMFlXeHZjekFlRncweU5UQXlNalF4T1RVNE1qZGFGdzB6TlRBeU1qSXhPVFU0TWpkYU1CQXhEakFNQmdOVgpCQW9UQlhSaGJHOXpNQ293QlFZREsyVndBeUVBYis3MXI1d3B3SDhrR09iY1lMQmxEeTZ6bTVsamxXOS91NjJSCkR2T0xoQTJqWVRCZk1BNEdBMVVkRHdFQi93UUVBd0lDaERBZEJnTlZIU1VFRmpBVUJnZ3JCZ0VGQlFjREFRWUkKS3dZQkJRVUhBd0l3RHdZRFZSMFRBUUgvQkFVd0F3RUIvekFkQmdOVkhRNEVGZ1FVNXVIOXE4Tk5YeDZHRldmSQpZdEQzenB1U3FYa3dCUVlESzJWd0EwRUE0ZmpmUW5JQkJiNURUSFZpM1pOWWwxTlI5MVdCNmZOVDd4R0ZBT0RCCnZOL3ZCaTNBZ1l4ZldHMDlRK04rS3liYTcwRkRLc1hLWmErOXpnUXByU3dpQUE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        key: LS0tLS1CRUdJTiBFRDI1NTE5IFBSSVZBVEUgS0VZLS0tLS0KTUM0Q0FRQXdCUVlESzJWd0JDSUVJSXNKa3orTGU3eVdJUFZ0VWMxL1hHOEpBVUJTRUZDWCsxbGZ6ZGE1WnlaKwotLS0tLUVORCBFRDI1NTE5IFBSSVZBVEUgS0VZLS0tLS0K
    certSANs:
        - talos-cp.fritz.box
    kubelet:
        image: ghcr.io/siderolabs/kubelet:v1.31.1
        defaultRuntimeSeccompProfileEnabled: true
        disableManifestsDirectory: true
    network:
        hostname: talos-cp
    install:
        disk: /dev/mmcblk0
        image: ghcr.io/siderolabs/installer:v1.8.0
        wipe: false
    features:
        rbac: true
        stableHostname: true
        apidCheckExtKeyUsage: true
        diskQuotaSupport: true
        kubePrism:
            enabled: true
            port: 7445
        hostDNS:
            enabled: true
            forwardKubeDNSToHost: true
    nodeLabels:
        node.device: raspi-4
        node.kubernetes.io/exclude-from-external-load-balancers: ""
        node.network-connect: switch
        node.storage: 32gb
        node.type: controlplane
cluster:
    id: nvC4S1UzbTcUB7rUES6nfMDhOedgTRBVPDYGauL96iw=
    secret: qsCmUXt8/i7k/6bdSQ+mI8u08zSYUspweip0lyuNI5w=
    controlPlane:
        endpoint: https://talos-cp.fritz.box:6443
    clusterName: talos-cluster
    network:
        dnsDomain: cluster.local
        podSubnets:
            - 10.244.0.0/16
        serviceSubnets:
            - 10.96.0.0/12
    token: sfqeeq.tihj2y7yahu4mh64
    secretboxEncryptionSecret: Iot+uEg8o6P8nGusKakzKQa9jxdP59aqSdFOQVlZWXQ=
    ca:
        crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJpRENDQVMrZ0F3SUJBZ0lRR3JMZXdtVGxtUWkrazZqdXVzb3gvakFLQmdncWhrak9QUVFEQWpBVk1STXcKRVFZRFZRUUtFd3ByZFdKbGNtNWxkR1Z6TUI0WERUSTFNREl5TkRFNU5UZ3lOMW9YRFRNMU1ESXlNakU1TlRneQpOMW93RlRFVE1CRUdBMVVFQ2hNS2EzVmlaWEp1WlhSbGN6QlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VICkEwSUFCRlo3dVZjR0FlVTVaSUMxOG56aTBadGM2WnRZcitudlNqYUYyek1BcHVLWXpKcTYrakt3YXg3STAveUEKOTdtSnFORGViMk9GbUtSRVlxNUxEVThzT3MrallUQmZNQTRHQTFVZER3RUIvd1FFQXdJQ2hEQWRCZ05WSFNVRQpGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFCkZnUVU1TFd5RXBpYXpMT1NYVjFnZ2laSFY4VFlYc2d3Q2dZSUtvWkl6ajBFQXdJRFJ3QXdSQUlnVm5HeERJN2kKdklmc3FKRzBYdnFmWmZjMUE3a0l5WkxrYWxtSGt4SnFOc2tDSUdzQ2pvdzZENHhyZVYzQ1A5Tmw5aXM2T3Y5YQpZbE1vL0hzVEJoNnd3ejFJCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
        key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSU1vclcrTzUzVmtaSUZOd1NhSGJ2T1lXOElDTUFpM0hrdlA1RUw5VEJlVGNvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFVm51NVZ3WUI1VGxrZ0xYeWZPTFJtMXpwbTFpdjZlOUtOb1hiTXdDbTRwak1tcnI2TXJCcgpIc2pUL0lEM3VZbW8wTjV2WTRXWXBFUmlya3NOVHl3Nnp3PT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
    aggregatorCA:
        crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJZRENDQVFXZ0F3SUJBZ0lRRzNQUzZleXEyYWd5UjBsRVJDRTFHekFLQmdncWhrak9QUVFEQWpBQU1CNFgKRFRJMU1ESXlOREU1TlRneU4xb1hEVE0xTURJeU1qRTVOVGd5TjFvd0FEQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxRwpTTTQ5QXdFSEEwSUFCT1RrNU4ydEhwNXNEZW1lWHd4cEVuQWZwRkZTVDlFcnA1T1p0N2dWaUM3WDQzaW4wRXJ3ClhtQW5YcTZPYWwwQTNieDVWeHp6V1N5UHV3c0toaXZleDVlallUQmZNQTRHQTFVZER3RUIvd1FFQXdJQ2hEQWQKQmdOVkhTVUVGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZApCZ05WSFE0RUZnUVVBejhQUk40VEdEOWQvRk9NUE1XUTFFZnFtNFV3Q2dZSUtvWkl6ajBFQXdJRFNRQXdSZ0loCkFLM1NRazNKUkY0cG5hT1dXZThCNFVKT2RaOWg2MFJJRUZldHNvZmRPbmIyQWlFQXU0RDYzUlFKZmlpMGpZVWMKSjJ2QnV3WFlsdk05ZG5FTi9Zb2NIYUNBK25FPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSU1mN28wdkxacUwyWjRvK2RIeUZud241OW1LQnpQdWRaYXk0bEdNcmtDYktvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFNU9UazNhMGVubXdONlo1ZkRHa1NjQitrVVZKUDBTdW5rNW0zdUJXSUx0ZmplS2ZRU3ZCZQpZQ2Rlcm81cVhRRGR2SGxYSFBOWkxJKzdDd3FHSzk3SGx3PT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
    serviceAccount:
        key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlKS0FJQkFBS0NBZ0VBMEVudG1yS2lQUEpjd2NVY2NHbEw5SVB3OW1rTlpkT1N6T1U5cjZvQm44d1EvcDB1CjM0dXp1WHJaNXZCcUNHWnByOXpsUG5FTHNnQXBDWTl5d3BoUTRCK3VVMTNHd1pEdDFHZ2toZFIranR2YU5sdCsKUFQvQmhYN1N5TEFyZ1NGaThlOGlmSVU3bjZpc0VkblM5NFNaRXhQOXk1WlBmdzJKUnZiUnAwaVp0UlYxZmlPZQo5OEZnaVVWWlBOamZrYm10ZmZSU3JZU1pXUjN0OUNXelNOWUM5Tm1CT2NQTlZiVDhGZXFZaWlkL2t4VEpQZ1dKClNUTTJBRzN0eGFTOGwwNFBJNHdMTFNzMTJCQ3J2bjFvWjFRampQaHZ1dUhOaWdSbmRYVUJ3dU1NUEE0QUhobkgKQ0dkWmxCSXYvVlZicUpCa2tpM1JOWWhoRHB1dXZLU3pCa0dqN0Exa0hNWWpPUmlpM1pKY1BtR1FuUkp0L3pGcQpHaUlwcEVBYlovM3RqTHBLcy9rY0hzRkVNcDZoN0ZOZVN0UzJyU3ZxM2E0YkFsd1V4MmxkQVV3Um10ZUFJWDV5CjUvQlpvUnNIei91QXgxcHhXbE5LTUtHMkpRM3lldEVTeGFFMWxEZUZPNHZNK0VTWGY4UkU0dENJMjNUK1k4MlMKVTNxRlYwZ09DUVdTNzVvZ3AvV2FOWE1Pd2FIZmxISER0OU9uVmJHRXBvTVoyRUYzZzdFVjFiMzY2VC8vUEQrbQpHQkRVczFMaEt0VFlIYVdwR0NvdVF0UzNvbnBieUx3M01QdW0wbjd1MzNEOFVoZ2daNGQ1Y0k2c0ZKWnBrYmFrCldWQm1NTGMyTHpNQXZCNWQ3YWo5T3BnR1UwZHVuUUtyWnVmRmVwTzNGUXdVUng1d2o4VjlERE5aaEs4Q0F3RUEKQVFLQ0FnQklieDB4S2lRZmU4MWtHVzh0YklEY2xMSE1qM1g0VGw2RDRNalYrUkk5aHhMMTZLV3ZXZjd6WnRTMgphaThGb3Mvb043S0ZSM3pndHd1T1pwTnJOdHNSUmhNeXJLNzlDN0NacUduakhLV3llcVJsT09ZcTJLd3RCNUMzCitBUDVFU28rcG9IZ3VkaWxTbHdralJLL3Z4NFlzMkFVVjc1bm1jWitwa0Q4b3RQSlZLQWFjTHJNd0RRWktNUEMKMUV6VGViWHEwbmVhSGozUjd3V2NYU3YvRFdYVHpud1JJWldiMDZmQzIyV1d6ZXVnczU3VWNjcHZhVjdEUVhkcAp2ME5TZnZQbTBjSGxRRnltT2czdjNkN2I2RGZBdzNqZmpiMFQzVG81YjZwZ0l1TlRVeThaU0srZHJZdEtZaFRNClRjM2xUZW1icUZGVUE0eDFMeERTUzVoeWVZdE9YOFRTYmV5djVtSmVjcktSSjVQR21zYlMwc1dJTmNtaGwwUDQKZVhnM0tMaExqc1RzcURZbVYrOGRhTnpDNmFNUWVnZEVoemhYTG5peW1jYnJUcGYxVVlScm12YkIyTDRrMHhmdQp0OE5mc3FEUkVTWmVJNjlOY2dtdXY3enJXc0tiUExQMWF0a3ZNM1gvUDdLd2JRWmp0ZjJqQU9ZcVJsNjh1aFpOCmdNNy9GVFNqR0NvTzYvTlNDM1Vta1RtaXFjTk5TZ0xtOUw4MW1lZFk5SU1QWTJoSlNxb1dPeEZLWTlpeHpQWXEKTWdZYlF3WFg0ZFYvdFB0NEdNR3JDTzd6SVh0QnNOdEptZFhML2lIL2pjemhXRXAzczFKcEM4cURicDdmOHlvVgozZkRNV0pMT25sOU9iYy9QRTc5MTdqOStSZVZYZWhNZ1A4M0JGSmU2TEZ4dkZDSEpXUUtDQVFFQStHTHBkTnVyCnpaTjE1RlpQYlMzMXQ3SmFLTUNGdC9HVnNxemhTMWJYQU9jYXk0d0UwaU1wL0R3ZkFSdUVCc3ppOHd3Z2dTblcKK3ZmYWxNbzh6LzhTNERONyt2U0pSTVlSQXRnSHlPdDZtbEp4TElaTm5xVjloZkJoayt1ZE5jcTBiZlFXSVlEcwpkTVdoSWMvR2tYL3F3SDJWeTVCK0tmMXVUUzRFWnJQMnA2SXZ1Z01OaUVzNEdDbG1nWmRuUlJaVDlvUzRKR3NuCnFoM0VzakJFLytEenJKRTNEZlFtMXYwNE5Vdm5YaUVDRFg2LzdaWkN6ZEJtYmZpcVgwMDB4aC8yK1ZiOUU5L2IKcjZhUlJWdFNGRFdoOG5KelBsY3d1anUzUkJDejg4eHVMVk92eDVxb3lNUjFPSTVIWEhVdjVkNW8yQm43MExIaAp3UWJ0TWZQbEhxWThGUUtDQVFFQTFxeGUwQWFZcU9IYjdKbHErSmtzbkZOMDJkZGkxNkFXaWpsald1OEpBNUE3CnMwcXJITmoxc2djMWtnbCtTMGVMM3BZSk0vRC9GM2xiU1JVTmFWc21kbWpMTjROTmtaaUNrV0I2SDdZcE14ZEQKekZEdytTL00rZ1JFMDljNThpYmNnK2FhQ0lMbnR1cEZHZFpUaGt2RzBKZDdzNFlWTXZTZzNvaitRd0dHWExrVAoxc0VxSGxjN3h4NFhUOHNLM2JCSENCQlV1WEJzazc3WjkyMU0wMXRoZWRPZWxWM1JJaFdDd2UwY2RsMFpPUThCCmZkOXV5UWhidTVWTDZrdzJkTDB0Qzh5ci96eVc1SzlmNUhUR3RLWXZvVFpNTjdndDZNY01rcHUyNUNWckRWSmQKREhDb1NOWFN2YUFrK0lxUXJCRnlBSUhQcU94M21rTGlzNkdsVSszNnN3S0NBUUVBOVBxcGcwWTk5cTVmOG10bQpQeXE3VlFpbGY5Z1Npcy9OYzhLckdtRjJBVC91MzU4a0NoWUFqUFRISjVKNTd6TVpDOXFFSEtDbGxqWHE4aUZkClJWQXd6OHczbGRhbHBKMHRuZjV2L3l5eGFZK3lhOVd5ckt4UVYxQTFEVzJ2U3FTNHZGR25tamZMLzRnRVdwTFIKS0NSZjVxWjJuYVhQcVo1NXNjbVhNYXlCcytoMDVpT29yeXB4RXZPU1ZISjl1bGhCUzd5dTJjeU4vRzBMMlN0ZQpnbmplSE8vRXV4QjVWa1c5c0dOQ3VVWVkvakpySGV1N3k3NmxxQVZBRkdyVGlDMXlxNDJ1WW5IQi9VWnR0VmhTClpmaFgyQVlsdi9EQzhJdUJQN0t4cWQyUk5VZDY4WVdLdnlsMDYrajRYU3AvcVZwcFVlcWV3TUVSQmc3TTF4M1UKZHh4QjJRS0NBUUJ1cExUUlh6VDdoajJGdXFVSnNGanYwWXZlWTBiTWYvUmVGYW9CeWtYSkVtUFN5dDlhcFBBdAphODNPa1JvSXpyMW1ZY29vZlVQYzQyMkxRMUNBUnJ5U052eldoZFJMQUdIN2I5QkIyKzlzSjhlSDNRZjJSdzdNCnBicWJ2TWhlNkd5cmh3Vkk4YjlmNVdyc0lDMDRnSUhlTE5WUzkvNmhIcmh6T2dSaW9MeVJ1Y3BoMjNsTDNnWXYKWUhEL2JWVVNZYkthazJBM201dzZvaGxSajRJVFJYditBSFl4NGdMU0lHZ2ViNGxGOEVINXlLUXFMaWk1Y0pkbgpIVkhkVnA2U21KWkpDSnAxbU5MazF3Y0RoclNMazBQbFFVa1RSdGhTcTVUdFUxaDJTbHJjcU9EUWNwZ3B3aHMyCkpQNHBJN0hoSGJTMlVqR25qUWt2OXQxRlhFRUwreEpGQW9JQkFFOUhvVHJQVWtIdEtESUVXOW9Rc0c5VjNVdmMKaitlcnRKd240OExkd2R6eW4yQS91QmtnZnpad0h5QklVajVXYWtLcUN1eUtBcFhKWVJuYXZpdTg4c09KTWFMVwplc2JuQnRXUEgxOXNraHlOVWljN0VxdmZSRjVzY1N0RzJkaW5JeHowSUQwdHNhblN6S2lzY0JIakNzeERoZGxpCnZyMG1hdkxSYnhKaWQrdlVsMndFZjV4L1crNnErWTFqUE5WMzFmbW0vL29yNHM0ZjJITkpjWWhEeE40ZCtiM1YKL0RZMWg4V0FEZnpWUFJkUzhEODhsZUF5em16R3BIbW1LbFNKVWFweldHc1N4NkFjaW9GelQ4MWdrN0RMdmh2ZQo3SXdLQmR1cC9TOHZDQStSSFlRTmdnMTU4S3JaYzlvdC9pejg1VklMYzdmUjR5TzA2VVlrK0lYbUlQTT0KLS0tLS1FTkQgUlNBIFBSSVZBVEUgS0VZLS0tLS0K
    apiServer:
        image: registry.k8s.io/kube-apiserver:v1.31.1
        certSANs:
            - talos-cp.fritz.box
        disablePodSecurityPolicy: true
        admissionControl:
            - name: PodSecurity
              configuration:
                apiVersion: pod-security.admission.config.k8s.io/v1alpha1
                defaults:
                    audit: restricted
                    audit-version: latest
                    enforce: baseline
                    enforce-version: latest
                    warn: restricted
                    warn-version: latest
                exemptions:
                    namespaces:
                        - kube-system
                    runtimeClasses: []
                    usernames: []
                kind: PodSecurityConfiguration
        auditPolicy:
            apiVersion: audit.k8s.io/v1
            kind: Policy
            rules:
                - level: Metadata
    controllerManager:
        image: registry.k8s.io/kube-controller-manager:v1.31.1
    proxy:
        image: registry.k8s.io/kube-proxy:v1.31.1
    scheduler:
        image: registry.k8s.io/kube-scheduler:v1.31.1
    discovery:
        enabled: true
        registries:
            kubernetes:
                disabled: true
            service: {}
    etcd:
        ca:
            crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJmVENDQVNTZ0F3SUJBZ0lSQU5OWU4xcDlTWng4SXc0VlRXZEhvUm93Q2dZSUtvWkl6ajBFQXdJd0R6RU4KTUFzR0ExVUVDaE1FWlhSalpEQWVGdzB5TlRBeU1qUXhPVFU0TWpkYUZ3MHpOVEF5TWpJeE9UVTRNamRhTUE4eApEVEFMQmdOVkJBb1RCR1YwWTJRd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFTYXFDODltdnltCitYbi9PNHdFSWFtWXlnMks5dFNaaERRUm1vb2RGbXBDajhqVDl3USt2aERmaTFKOGlpS1B3a3VCYkdMNXB3VnoKTmo0SWQrTWVsdVY2bzJFd1h6QU9CZ05WSFE4QkFmOEVCQU1DQW9Rd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSApBd0VHQ0NzR0FRVUZCd01DTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3SFFZRFZSME9CQllFRk8wbzVBZ0tlM1NvCmNSUVc4SEVmU0NtK1RFL3VNQW9HQ0NxR1NNNDlCQU1DQTBjQU1FUUNJRkRBN3FLdTloRGxwWjg3V1ovd0RlMDAKbnZNL1BzRXFXM0MxVjZQTmtQdlhBaUJtUlEvbklyOTNMRlBJQmd4Mjd0VnpRK3YzOHVVSmt1dDVWWURGN1BpMwphdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
            key: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUlZYWhvWGYzY3hSNlFEUkhZUlBNcnRTNE4zUVB1bzA4VDdZekF5cGo4VUtvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFbXFndlBacjhwdmw1L3p1TUJDR3BtTW9OaXZiVW1ZUTBFWnFLSFJacVFvL0kwL2NFUHI0UQozNHRTZklvaWo4SkxnV3hpK2FjRmN6WStDSGZqSHBibGVnPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
