---
- name: Packages Ubuntu  ----  Uninstall  ----  Pre-installed packages
  ansible.builtin.apt:
    pkg:
      - thunderbird
      - libreoffice
      - libreoffice-*
      - totem
      - totem-*
    state: absent

- name: Packages Ubuntu  ----  Uninstall  ----  Other packages
  ansible.builtin.apt:
    pkg:
      - yarn
      - google-chrome-stable
    state: absent

- name: Packages Ubuntu  ----  Uninstall  ----  Pre-installed snap packages
  community.general.snap:
    name:
      - thunderbird
    state: absent
