---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: hello-world-nginx-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sommerfeld-io/configs-homelab.git
    targetRevision: main
    path: components/talos-cluster/helm-charts/hello-world-nginx
    helm:
      valuesObject:
        nodePort: 32080
        replicas: 2
  destination:
    server: https://kubernetes.default.svc
    namespace: hello-world-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
