---
version: '3.42.1'

tasks:

  system:info:
    desc: 'Show system information'
    cmds:
      - hostnamectl
      - 'echo -e " ${B}Ubuntu Codename:${D} $(lsb_release -c | cut -f2)"'
    silent: true

  # ===============================================================================================

  port-forward:argocd:
    vars:
      NAMESPACE: argocd
      PORT: 8080
      SVC_PORT: 80
    desc: 'Forward port for ArgoCD'
    cmds:
      - kubectl -n "{{.NAMESPACE}}" get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d
      - echo -e "URL = ${Y}https://localhost:{{.PORT}}${D}"
      - kubectl port-forward -n "{{.NAMESPACE}}" svc/argocd-server "{{.PORT}}:{{.SVC_PORT}}" --address 0.0.0.0

  port-forward:prometheus:
    vars:
      NAMESPACE: telemetry
      PORT: 9000
      SVC_PORT: 9090
    desc: 'Forward port for Prometheus'
    cmds:
      - echo -e "URL = ${Y}http://localhost:{{.PORT}}${D}"
      - kubectl port-forward -n "{{.NAMESPACE}}" svc/prometheus-operated "{{.PORT}}:{{.SVC_PORT}}" --address 0.0.0.0
