---
machine:
  network:
    hostname: talos-w4
  install:
    disk: /dev/mmcblk0
  certSANs:
    - talos-w4.fritz.box
  nodeLabels:
    node.network-connect: switch
    node.device: raspi-5
    node.storage: 32gb
    node.type: worker
