# -*- mode: ruby -*-
# vi: set ft=ruby :

require "socket"

BOX_NAME = "cloud-image/ubuntu-26.04"
VM_HOSTNAME = "vagrant-#{Socket.gethostname}-ollama"

Vagrant.configure("2") do |config|
  config.vm.box = BOX_NAME
  config.vm.hostname = VM_HOSTNAME

  config.vm.disk :disk, size: "100GB", primary: true

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false

    vb.cpus = 5
    vb.memory = 9 * 1024
    vb.name = VM_HOSTNAME

    vb.customize ["modifyvm", :id, "--vram", "128"]
    vb.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
  end

  # Networking: Bridged allows other devices in your homelab to access Ollama
  # Change to "private_network" if you want it isolated to the host
  # config.vm.network "public_network", use_dhcp_assigned_default_route: true

  config.vm.cloud_init do |cloud_init|
    cloud_init.content_type = "text/cloud-config"
    cloud_init.inline = <<-EOF
      timezone: Europe/Berlin
      package_update: true
      package_upgrade: true
    EOF
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "ansible-playbook.yml"
    ansible.extra_vars = {
      "ansible_user" => "vagrant",
      "ps1" => '${debian_chroot:+($debian_chroot)}\[\033[01;33m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\] $ ',
      "ps1_root" => '${debian_chroot:+($debian_chroot)}\[\033[1;38;5;213m\]\u@\h:\[\033[1;34m\]\w\[\033[00m\] $ ',
      "architecture" => "amd64",
        "ollama_models" => [
          "tinyllama",
          # "gemma4:e2b",
          # "gemma4:e4b"
        ],
      "dir_work" => "/home/{{ ansible_user }}/work",
      "dir_repos" => "{{ dir_work }}/repos",
      "dir_repos_bad_android" => "{{ dir_repos }}/bad-android",
      "dir_repos_sommerfeld_io" => "{{ dir_repos }}/sommerfeld-io",
      "dir_repos_sommerfeld_io_archive" => "{{ dir_repos }}/sommerfeld-io-archive",
      "dir_repos_sebastian_sommerfeld_io" => "{{ dir_repos }}/sebastian-sommerfeld-io"
    }
  end
end
