---
- name: Talos  ----  Admin Pi  ----  Write aliases to .bash_aliases
  ansible.builtin.lineinfile:
    create: true
    mode: 0600
    dest: "/home/{{ ansible_user }}/.bash_aliases"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    line: "{{ item }}"
    state: present
  with_items:
    - alias talosctl-cp="talosctl --nodes {{ control_plane_node }} --endpoints {{ control_plane_node }}"
    - alias talosctl-w1="talosctl --nodes talos-w1.fritz.box --endpoints {{ control_plane_node }}"
    - alias talosctl-w2="talosctl --nodes talos-w2.fritz.box --endpoints {{ control_plane_node }}"
    - alias talosctl-w3="talosctl --nodes talos-w3.fritz.box --endpoints {{ control_plane_node }}"
