---
- name: Talos  ----  Copy scripts for user {{ ansible_user }}
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "/home/{{ ansible_user }}/{{ item.dest }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: u=rwx,g=rx,o=rx
  with_items:
    - { src: "../assets/scripts/bootstrap-argocd.sh", dest: "bootstrap/bootstrap-argocd.sh" }
    - { src: "../assets/scripts/bootstrap-talos.sh", dest: "bootstrap/bootstrap-talos.sh" }

- name: Talos  ----  Copy node configs
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "/home/{{ ansible_user }}/{{ item.dest }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: u=rw,g=r,o=r
  with_items:
    - { src: "../assets/node-configs/talos-cp-patch.yml", dest: "bootstrap/talos-cp-patch.yml" }
    - { src: "../assets/node-configs/talos-w1-patch.yml", dest: "bootstrap/talos-w1-patch.yml" }
    - { src: "../assets/node-configs/talos-w2-patch.yml", dest: "bootstrap/talos-w2-patch.yml" }
    - { src: "../assets/node-configs/talos-w3-patch.yml", dest: "bootstrap/talos-w3-patch.yml" }
    - { src: "../assets/node-configs/talos-w4-patch.yml", dest: "bootstrap/talos-w4-patch.yml" }
