---
- name: Talos  ----  Admin Pi  ----  Download k9s .deb package
  ansible.builtin.get_url:
    url: https://github.com/derailed/k9s/releases/download/{{ version }}/k9s_linux_{{ architecture }}.deb
    dest: /tmp/k9s_linux_{{ architecture }}.deb
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
  vars:
    version: v0.32.7

- name: Talos  ----  Admin Pi  ----  Install k9s .deb package
  ansible.builtin.apt:
    deb: /tmp/k9s_linux_{{ architecture }}.deb
    state: present

# - name: Talos  ----  Admin Pi  ----  Clean up the downloaded .deb file
#   ansible.builtin.file:
#     path: /tmp/k9s_linux_{{ architecture }}.deb
#     state: absent
