---
- name: Omarchy Customizations  ----  GitHub Theme
  ansible.builtin.import_tasks: themes/github/main.yml

- name: Omarchy Customizations  ----  Keybindings
  ansible.builtin.import_tasks: keybindings/main.yml
