---
- name: Task Config  ----  Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: u=rwx,g=rx,o=rx
  with_items:
    - "/home/{{ ansible_user }}/.docker-stacks"

- name: Task Config  ----  Copy taskfile and configs
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: u=rwx,g=rx,o=rx
  with_items:
    - { src: "../assets/docker-stacks/ops", dest: "/home/{{ ansible_user }}/.docker-stacks" }
    - { src: "../assets/docker-stacks/portainer", dest: "/home/{{ ansible_user }}/.docker-stacks" }
    - { src: "../assets/global-taskfile.yml", dest: "/home/{{ ansible_user }}/taskfile.yml" }
