---
- name: Install  ****  Basic packages
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - software-properties-common
      - make
      - ncdu
      - htop
      - neofetch
      - python3-pip # python package manager
      - vim
    state: latest
    update_cache: true
