---
- name: Config  ----  Create directories for scripts
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: u=rwx,g=rx,o=rx
  with_items:
    - /opt/scripts

- name: Config  ----  Copy scripts
  ansible.builtin.copy:
    src: "../assets/scripts/{{ item }}.sh"
    dest: "/opt/scripts/{{ item }}.sh"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: u=rwx,g=rx,o=rx
  with_items:
    - system-info

- name: Config  ----  Create symlinks to scripts in /usr/bin
  ansible.builtin.file:
    src: "/opt/scripts/{{ item }}.sh"
    dest: "/usr/bin/{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: link
  with_items:
    - system-info
