---
- name: Uninstall  ----  Scripts
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /usr/bin/switch-display-inputs
    - /opt/scripts/switch-display-inputs.sh
    - /usr/bin/system-info
    - /opt/scripts/system-info.sh
    - /opt/scripts
    - /usr/bin/jarvis
    - /opt/jarvis
    - /tmp/bash-lib

- name: Uninstall  ----  Docker wrapper scripts
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /opt/docker-wrappers/groovy.sh
    - /opt/docker-wrappers/hadolint.sh
    - /opt/docker-wrappers/mvn.sh
    - /opt/docker-wrappers/node-npm.sh
    - /opt/docker-wrappers/shellcheck.sh
    - /opt/docker-wrappers/yamllint.sh
    - /opt/docker-wrappers/node.sh
    - /opt/docker-wrappers/npm.sh
    - /opt/docker-wrappers
    - /usr/bin/groovy
    - /usr/bin/hadolint
    - /usr/bin/mvn
    - /usr/bin/node-npm
    - /usr/bin/shellcheck
    - /usr/bin/yamllint
    - /usr/bin/node
    - /usr/bin/npm

- name: Uninstall  ----  Docker Stacks
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/home/{{ ansible_user }}/.docker-stacks/ops"
