---
- name: SSH Config  ----  Create ssh keypair
  community.crypto.openssh_keypair:
    path: "/home/{{ ansible_user }}/.ssh/id_rsa"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    type: rsa
    size: 4096
    state: present
    force: false
