---
- name: Config  ----  Download and execute the atuin setup script
  ansible.builtin.shell:
    cmd: "curl --proto '=https' --tlsv1.2 -LsSf https://setup.atuin.sh | bash"
  args:
    executable: /bin/bash
    creates: "/home/{{ ansible_user }}/.atuin/bin/atuin"
