---
- name: Wallpaper  ----  Copy scripts for user {{ ansible_user }}
  ansible.builtin.copy:
    src: "../assets/scripts/talos/{{ item }}"
    dest: "/home/{{ ansible_user }}/{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: u=rwx,g=rx,o=rx
  with_items:
    - argocd-port-forward.sh
    - docker-stacks-cli.sh
