---
- name: Install  ****  Chromium packages
  ansible.builtin.apt:
    pkg:
      - chromium-browser
      - chromium-browser-l10n
      - chromium-codecs-ffmpeg
    state: latest
    update_cache: true

# - name: Install  ****  Download Chrome package
#   ansible.builtin.uri:
#     url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
#     dest: /tmp/chrome.deb
#     status_code: [200, 301, 302, 304]

# - name: Install  ****  Chrome
#   ansible.builtin.apt:
#     deb: /tmp/chrome.deb

# - name: Install  ****  Chrome cleanup
#   ansible.builtin.file:
#     path: /tmp/chrome.deb
#     state: absent

- name: Uninstall  ****  Chrome package
  ansible.builtin.apt:
    pkg:
      - google-chrome-stable
    state: absent
    update_cache: true
