---
- name: Docker Setup  ----  Purge deprecated docker installations
  ansible.builtin.apt:
    pkg:
      - docker
      - docker-compose
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent
    update_cache: true

- name: Docker Setup ---- Download Docker GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    # dest: /etc/apt/keyrings/docker.gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Docker Setup ---- Add apt repository (OS-codename {{ codename }})
  ansible.builtin.apt_repository:
    # repo: "deb [signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ codename }} stable"
    repo: "deb [signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ codename }} stable"
    filename: docker
    state: present
  vars:
    codename: "{{ ansible_distribution_release }}"
    # codename: noble # No official support for Ubuntu 25.04 yet - https://docs.docker.com/engine/install/ubuntu/#os-requirements

- name: Docker Setup  ----  Install docker packages
  ansible.builtin.apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest
    update_cache: true

- name: Docker Setup  ----  Add user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    shell: /bin/bash
    groups: docker
    append: true

- name: Docker Setup  ----  Verify Docker installation
  ansible.builtin.command: docker version
  register: docker_version_output

- name: Docker Setup  ----  Print Docker version
  ansible.builtin.debug:
    msg: "{{ docker_version_output.stdout }}"

- name: Docker Setup  ----  Verify Docker Compose installation
  ansible.builtin.command: docker compose version
  register: docker_compose_version_output

- name: Docker Setup  ----  Print Docker Compose version
  ansible.builtin.debug:
    msg: "{{ docker_compose_version_output.stdout }}"
