---
- name: Uninstall  ----  Pre-installed packages
  ansible.builtin.apt:
    pkg:
      - thunderbird
      - libreoffice
      - libreoffice-*
      - totem
      - totem-*
    state: absent

- name: Uninstall  ----  Pre-installed snap packages
  community.general.snap:
    name:
      - thunderbird
    state: absent

- name: Uninstall  ----  Remove directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /home/{{ ansible_user }}/.config/libreoffice
