---
- name: Config  ****  Clone mandatory git repositories from Github (github.com/sommerfeld-io)
  ansible.builtin.git:
    repo: "git@github.com:sommerfeld-io/{{ item }}.git"
    dest: "/home/{{ ansible_user }}/work/repos/sommerfeld-io/{{ item }}"
    key_file: "/home/{{ ansible_user }}/.ssh/id_rsa"
  with_items:
    - configs-homelab
