---
- name: Config -> Write aliases to .bashrc (for Ubuntu desktop)
  ansible.builtin.lineinfile:
    create: true
    mode: 0600
    dest: "/home/{{ ansible_user }}/.bash_aliases"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    line: "{{ item }}"
    state: present
  with_items:
    - alias reset-conky="(killall conky && cd /home/{{ ansible_user }}/work/repos/sommerfeld-io/configs-homelab/components/conky && ./run.sh)"
