---
- name: Uninstall  ----  Pre-installed packages
  ansible.builtin.apt:
    pkg:
      - thunderbird
      - libreoffice
      - libreoffice-*
      - totem
      - totem-*
      - yarn
    state: absent

- name: Uninstall  ----  Pre-installed snap packages
  community.general.snap:
    name:
      - thunderbird
    state: absent
