---
- name: Uninstall  ----  Some pre-installed packages
  ansible.builtin.apt:
    pkg:
      - thunderbird
      - libreoffice
      - libreoffice-*
      - totem
      - totem-*
    state: absent

- name: Uninstall  ----  Some pre-installed snap packages
  community.general.snap:
    name:
      - thunderbird
    state: absent
