---
- name: Virtualbox Setup
  block:

    - name: Virtualbox Setup ---- Install Virtualbox and dependencies
      ansible.builtin.apt:
        pkg:
          - virtualbox
          - virtualbox-qt
          - virtualbox-dkms
        state: latest
        update_cache: true

    - name: Virtualbox Setup ---- Create virtual machines folder
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: u=rwx,g=rx,o=rx
      with_items:
        - "/home/{{ ansible_user }}/virtualmachines"

    - name: Virtualbox Setup ---- Set virtual machines folder
      ansible.builtin.command: "vboxmanage setproperty machinefolder /home/{{ ansible_user }}/virtualmachines"
      become: true
      become_user: "{{ ansible_user }}"

    - name: Virtualbox Setup ---- Add user to group
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        shell: /bin/bash
        groups: vboxusers
        append: true

- name: Vagrant Setup
  block:

    - name: Vagrant Setup ---- Download and convert HashiCorp GPG key
      ansible.builtin.shell: |
        curl -fsSL https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /etc/apt/keyrings/hashicorp-archive-keyring.gpg
      args:
        creates: /etc/apt/keyrings/hashicorp-archive-keyring.gpg

    - name: Vagrant Setup ---- Add apt repository (OS-codename {{ codename }})
      ansible.builtin.apt_repository:
        repo: "deb https://apt.releases.hashicorp.com {{ codename }} main"
        filename: hashicorp
        state: present
      vars:
        codename: "{{ ansible_distribution_release }}"
        # codename: noble # HashiCorp supports only LTS releases - so dynamically setting the distribution release might not work

    - name: Vagrant Setup ---- Install Vagrant packages
      ansible.builtin.apt:
        pkg:
          - vagrant
        state: latest
        update_cache: true

    - name: Vagrant Setup ---- Install Vagrant plugins
      ansible.builtin.shell: |
        vagrant plugin install vagrant-cachier
        # vagrant plugin install vagrant-vbguest
        # vagrant plugin install vagrant-docker-compose
      become: true
      become_user: "{{ ansible_user }}"
      args:
        executable: /bin/bash

    - name: Vagrant Setup ---- Verify installation
      ansible.builtin.command: vagrant --version
      register: vagrant_version_output
      changed_when: false

    - name: Vagrant Setup ---- Print version
      ansible.builtin.debug:
        msg: "{{ vagrant_version_output.stdout }}"
