---
- name: Services  ----  Telemetry Monitoring Stack  ----  Create and start services
  community.docker.docker_compose_v2:
    project_src: "{{ services_stack_telemetry }}"
    wait: true
    wait_timeout: 300 # seconds
  environment:
    HOSTNAME: "{{ ansible_hostname }}"
  register: output

- name: Services  ----  Telemetry Monitoring Stack  ----  Verify that services are running
  ansible.builtin.assert:
    that:
      - prometheus_container.State == 'running'
      - grafana_container.State == 'running'
      - blackbox_exporter_container.State == 'running'
  vars:
    ## Attribute `Services` refers to the name of the respective service in the docker-compose.yml file. So the
    ## they must match those defined in https://github.com/sommerfeld-io/telemetry/blob/main/components/telemetry/docker-compose.yml.
    ## Attribute `State` refers to the current state of the container (e.g. running, exited, etc.).
    prometheus_container: >-
      {{ output.containers | selectattr("Service", "equalto", "prometheus") | first }}
    grafana_container: >-
      {{ output.containers | selectattr("Service", "equalto", "grafana") | first }}
    blackbox_exporter_container: >-
      {{ output.containers | selectattr("Service", "equalto", "blackbox_exporter") | first }}
