---
- name: Setup for group raspi_talos_admin
  hosts: all
  gather_facts: true
  become: true
  vars_files:
    - ../../../ansible/vars/global.yml
    - vars.yml
  tasks:

    - ansible.builtin.import_tasks: ../../../ansible/tasks/common-bash-aliases.yml
    - ansible.builtin.import_tasks: ../../../ansible/tasks/common-bash-prompt.yml
    - ansible.builtin.import_tasks: ../../../ansible/tasks/common-create-directories.yml
    - ansible.builtin.import_tasks: ../../../ansible/tasks/common-task-setup.yml
    - ansible.builtin.import_tasks: tasks/install-packages.yml
    - ansible.builtin.import_tasks: tasks/install-k9s.yml
    - ansible.builtin.import_tasks: tasks/argocd-autopilot.yml

- name: Setup for group raspi_talos_admin (non-root)
  hosts: all
  gather_facts: true
  become: false
  vars_files:
    - ../../../ansible/vars/global.yml
    - vars.yml
  tasks:

    - ansible.builtin.import_tasks: tasks/bash-aliases.yml
    - ansible.builtin.import_tasks: ../../../ansible/tasks/common-atuin.yml

    - name: Config  ----  Create directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: u=rwx,g=rx,o=rx
      with_items:
        - "/home/{{ ansible_user }}/.talos"
        - "/home/{{ ansible_user }}/bootstrap"

    - ansible.builtin.import_tasks: tasks/copy-files.yml
    - ansible.builtin.import_tasks: tasks/clone-repos.yml

    - name: Talos  ----  Copy scripts, files and configs for user {{ ansible_user }}
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: u=rwx,g=rx,o=rx
      with_items:
        - { src: "assets/node-configs/generated/talosconfig.yaml", dest: "/home/{{ ansible_user }}/.talos/config" }
        - { src: "assets/taskfile.yml", dest: "/home/{{ ansible_user }}/taskfile.yml" }

    - name: Talos  ----  Generate kubeconfig
      command: talosctl kubeconfig --nodes "{{ control_plane_node }}" --endpoints "{{ control_plane_node }}"
