---
- name: Bash  ----  SSH  ----  Create ssh keypair
  community.crypto.openssh_keypair:
    path: "/home/{{ ansible_user }}/.ssh/id_rsa"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    type: rsa
    size: 4096
    state: present
    force: false

- name: Bash  ----  SSH  ----  Set permissions for public key
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/.ssh/id_rsa.pub"
    mode: '0640'
