apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  namespace: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      nodeSelector:
        kubernetes.io/hostname: talos-w3
      containers:
        - name: pihole
          image: pihole/pihole:2024.07.0
          ports:
            - containerPort: 80
          env:
            - name: WEBPASSWORD
              value: "admin"
          volumeMounts:
            - name: pihole-config
              mountPath: /etc/pihole
            - name: dnsmasq-config
              mountPath: /etc/dnsmasq.d
          readinessProbe:
            httpGet:
              path: /admin
              port: 80
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /admin
              port: 80
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 20
            failureThreshold: 3
      volumes:
        - name: pihole-config
          emptyDir: {}
        - name: dnsmasq-config
          emptyDir: {}
