---
apiVersion: v1
kind: Service
metadata:
  name: pihole-web-ui
  namespace: pihole
spec:
  selector:
    app: pihole
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
