---
- name: Block  ----  Clone repositories
  block:
    - name: Config  ----  Get status
      ansible.builtin.stat:
        path: "{{ item.dest }}/{{ item.repo }}"
      register: repo_directory_status
      loop: "{{ repositories }}"
      loop_control:
        label: "Check {{ item.dest }}/{{ item.repo }}"
    - name: Config  ----  Clone repo if not existing
      ansible.builtin.git:
        repo: "{{ github }}:{{ item.item.org }}/{{ item.item.repo }}.git"
        dest: "{{ item.item.dest }}/{{ item.item.repo }}"
        clone: true
        update: false
        key_file: "/home/{{ ansible_user }}/.ssh/id_rsa"
        accept_hostkey: true
      when: not item.stat.exists
      loop: "{{ repo_directory_status.results }}"
      loop_control:
        label: "Clone {{ github }}:{{ item.item.org }}/{{ item.item.repo }}.git"
