---
- name: Ping all nodes on the homelab
  hosts: all
  gather_facts: false
  become: false
  tasks:

    - name: Ping nodes
      ansible.builtin.ping:

    - name: Network  ----  Check network route metrics
      block:
        - name: Network  ----  Show default routes with metrics
          ansible.builtin.command: ip route show default
          register: routes
          changed_when: false
        - name: Network  ----  Print routes
          ansible.builtin.debug:
            var: routes.stdout_lines

    - name: Network  ----  Check all interface link states
      block:
        - name: Network  ----  Show all interfaces
          ansible.builtin.command: ip -brief link show
          register: ip_links
          changed_when: false
        - name: Network  ----  Print interfaces
          ansible.builtin.debug:
            var: ip_links.stdout_lines

    - name: Network  ----  Show IP addresses on real interfaces
      block:
        - name: Network  ----  Get IP addresses for ethernet and wifi interfaces
          ansible.builtin.shell:
            cmd: ip -brief -4 addr show | grep -vE '^lo|^docker|^br-|^veth|^virbr'
          register: ip_addrs
          changed_when: false
          failed_when: false
        - name: Network  ----  Print IP addresses
          ansible.builtin.debug:
            var: ip_addrs.stdout_lines
