---
- name: Prepare directories for git repositories
  hosts: ubuntu_desktop:ubuntu_server:raspi
  gather_facts: true
  become: true
  vars_files:
    - ../vars/main.yml
  tasks:
    - ansible.builtin.include_role:
        name: ../roles/ansible-roles-collection/filesystem

- name: Clone git repositories
  hosts: ubuntu_desktop
  gather_facts: true
  become: false
  vars_files:
    - ../vars/main.yml
  tasks:
    - ansible.builtin.include_role:
        name: ../roles/ansible-roles-collection/git-repositories
        tasks_from: main
      vars:
        git_repositories_ssh_base: &ssh-base git@github.com
        repositories:
          - { dest: "{{ dir_repos_sommerfeld_io }}", org: "sommerfeld-io", repo: ".github" }
          - { dest: "{{ dir_repos_sommerfeld_io }}", org: "sommerfeld-io", repo: ".task" }
          - { dest: "{{ dir_repos_sommerfeld_io }}", org: "sommerfeld-io", repo: ".vscode" }
          - { dest: "{{ dir_repos_sommerfeld_io }}", org: "sommerfeld-io", repo: "ansible-roles-collection" }
          - { dest: "{{ dir_repos_sommerfeld_io }}", org: "sommerfeld-io", repo: "configs-homelab" }
          - { dest: "{{ dir_repos_sommerfeld_io }}", org: "sommerfeld-io", repo: "container-images" }
          - { dest: "{{ dir_repos_sommerfeld_io }}", org: "sommerfeld-io", repo: "inspec-profiles" }
          - { dest: "{{ dir_repos_sommerfeld_io }}", org: "sommerfeld-io", repo: "skills" }
          - { dest: "{{ dir_repos_sommerfeld_io }}", org: "sommerfeld-io", repo: "tech-radar" }
          - { dest: "{{ dir_repos_sommerfeld_io }}", org: "sommerfeld-io", repo: "template-repository" }
          - { dest: "{{ dir_repos_sebastian_sommerfeld_io }}", org: "sebastian-sommerfeld-io", repo: "bookmarks" }
          - { dest: "{{ dir_repos_sebastian_sommerfeld_io }}", org: "sebastian-sommerfeld-io", repo: "gatus" }
          - { dest: "{{ dir_repos_sebastian_sommerfeld_io }}", org: "sebastian-sommerfeld-io", repo: "mkdocs-material" }
          - { dest: "{{ dir_repos_sebastian_sommerfeld_io }}", org: "sebastian-sommerfeld-io", repo: "tabler" }
          - { dest: "{{ dir_repos_bad_android }}", org: "bad-android", repo: ".github" }
          - { dest: "{{ dir_repos_bad_android }}", org: "bad-android", repo: "nhl-predictions-game-prototype" }

- name: Cleanup
  hosts: ubuntu_desktop:ubuntu_server:raspi
  gather_facts: true
  become: false
  vars_files:
    - ../vars/main.yml
  tasks:

    - name: Git Repositories  ----  Remove outdated repositories from host
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ dir_repos_sommerfeld_io }}/gatus-status-page"
        - "{{ dir_repos_sommerfeld_io }}/release-watcher"
        - "{{ dir_repos_sommerfeld_io }}/talos-runtime"
        - "{{ dir_repos_sommerfeld_io }}/telemetry"
