---
- name: Telemetry  ----  Metrics  ----  Create and start services
  community.docker.docker_compose_v2:
    project_src: "{{ telemetry_stack_metrics }}"
    wait: true
    wait_timeout: 60 # seconds
  register: output

- name: Telemetry  ----  Metrics  ----  Verify that services are running
  ansible.builtin.assert:
    that:
      - alloy_container.State == 'running'
      - node_exporter_container.State == 'running'
      - cadvisor_container.State == 'running'
  vars:
    alloy_container: >-
      {{ output.containers | selectattr("Service", "equalto", "alloy") | first }}
    node_exporter_container: >-
      {{ output.containers | selectattr("Service", "equalto", "node_exporter") | first }}
    cadvisor_container: >-
      {{ output.containers | selectattr("Service", "equalto", "cadvisor") | first }}
