---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-demo
  namespace: apache-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apache-demo
  template:
    metadata:
      labels:
        app: apache-demo
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - apache-demo
                topologyKey: kubernetes.io/hostname
      containers:
        - name: apache
          image: httpd:2.4.62-alpine3.21
          ports:
            - containerPort: 80
