---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  name: apache-demo
  namespace: apache-demo
  labels:
    app: apache-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apache-demo
  template:
    metadata:
      labels:
        app: apache-demo
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - apache-demo
                topologyKey: kubernetes.io/hostname
      containers:
        - name: apache
          image: httpd:2.4.62-alpine3.21
          ports:
            - containerPort: &containerPort 80
          readinessProbe:
            httpGet:
              path: /
              port: *containerPort
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: *containerPort
            initialDelaySeconds: 10
            periodSeconds: 15
      restartPolicy: Always
