---
apiVersion: v1
kind: Service
metadata:
  name: apache-demo-svc
  namespace: apache-demo
  labels:
    app: apache-demo
spec:
  selector:
    app: apache-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30082
  type: NodePort
  # type: ClusterIP
