---
apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  name: apache-demo
  namespace: apache-demo
  labels:
    app: apache-demo
    monitoring.sommerfeld.io/blackbox: enabled
spec:
  selector:
    app: apache-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30082
  type: NodePort
  # type: ClusterIP
