---
- name: Mount Disk  ----  Ensure mount directory exists
  ansible.builtin.file:
    path: "{{ mount_path }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: Mount Disk  ----  Mount and enable the SSD in fstab
  ansible.posix.mount:
    path: "{{ mount_path }}"
    src: "UUID={{ disk_uuid }}"
    fstype: ext4
    opts: defaults,noatime,nofail
    state: mounted
