---
version: '3.42.1'

tasks:

  docker:stack:ops:start:
    vars: &docker-stack-ops
      STACK: ops
    desc: &docker-stack-desc 'Docker stack = {{.STACK}} (start|stop|logs)'
    dir: &docker-stack-dir ~/.docker-stacks/{{.STACK}}
    cmds: &docker-stack-cmd-start
      - docker compose up -d

  docker:stack:ops:stop:
    vars: *docker-stack-ops
    desc: *docker-stack-desc
    dir: *docker-stack-dir
    cmds: &docker-stack-cmd-stop
      - docker compose down --volumes --remove-orphans

  docker:stack:ops:logs:
    vars: *docker-stack-ops
    desc: *docker-stack-desc
    dir: *docker-stack-dir
    cmds: &docker-stack-cmd-logs
      - docker compose logs -f

  docker:stack:portainer:start:
    vars: &docker-stack-portainer
      STACK: portainer
    desc: *docker-stack-desc
    dir: *docker-stack-dir
    cmds: *docker-stack-cmd-start

  docker:stack:portainer:stop:
    vars: *docker-stack-portainer
    desc: *docker-stack-desc
    dir: *docker-stack-dir
    cmds: *docker-stack-cmd-stop

  docker:stack:portainer:logs:
    vars: *docker-stack-ops
    desc: *docker-stack-desc
    dir: *docker-stack-dir
    cmds: *docker-stack-cmd-logs

  # ===============================================================================================

  minikube:start:
    desc: &minikube-desc 'Minikube (start|stop|dashboard|pods|services|status|destroy)'
    cmds:
      - minikube start
      - sleep 5s
      - minikube addons enable metrics-server
      - minikube addons enable ingress

  minikube:stop:
    desc: *minikube-desc
    cmds:
      - minikube stop

  minikube:dashboard:
    desc: *minikube-desc
    cmds:
      - minikube dashboard

  minikube:pods:
    desc: *minikube-desc
    cmds:
      - minikube kubectl -- get po -A

  minikube:services:
    desc: *minikube-desc
    cmds:
      - minikube service list

  minikube:status:
    desc: *minikube-desc
    cmds:
      - minikube version
      - helm version
      - minikube status

  minikube:destroy:
    desc: *minikube-desc
    cmds:
      - minikube delete

  # ===============================================================================================

  screen:caprica:
    vars: &screen-vars
      MONITOR_LEFT: "5" # Curved (landscape) /dev/i2c-5
      MONITOR_RIGHT: "4" # UHD (portrait) /dev/i2c-4
      CHANGE_INPUT_SOURCE: "0x60"
      SOURCE_HDMI_1: "0x11"
      SOURCE_HDMI_2: "0x12"
      SOURCE_DP: "0x0f"
    desc: &screen-desc 'Switch inputs sources for screens'
    cmds:
      - ddcutil -b {{.MONITOR_LEFT}} setvcp {{.CHANGE_INPUT_SOURCE}} {{.SOURCE_DP}}
      - ddcutil -b {{.MONITOR_RIGHT}} setvcp {{.CHANGE_INPUT_SOURCE}} {{.SOURCE_HDMI_1}}

  screen:office:
    vars: *screen-vars
    desc: *screen-desc
    cmds:
      - ddcutil -b {{.MONITOR_LEFT}} setvcp {{.CHANGE_INPUT_SOURCE}} {{.SOURCE_HDMI_2}}
      - ddcutil -b {{.MONITOR_RIGHT}} setvcp {{.CHANGE_INPUT_SOURCE}} {{.SOURCE_HDMI_2}}

  # ===============================================================================================

  ssh:connect:kobol:
    vars:
      USER: sebastian
      HOST: kobol.fritz.box
    desc: &ssh-connect-desc 'SSH connect {{.USER}}@{{.HOST}}'
    cmds: &ssh-connect-cmd
      - ssh {{.USER}}@{{.HOST}}

  ssh:connect:caprica:
    vars:
      USER: sebastian
      HOST: caprica.fritz.box
    desc: *ssh-connect-desc
    cmds: *ssh-connect-cmd

  # ===============================================================================================

  system:info:
    desc: 'Show system information'
    cmds:
      - hostnamectl
      - 'echo -e " ${B}Ubuntu Codename:${D} $(lsb_release -c | cut -f2)"'
    silent: true
