---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kroki
  namespace: kroki
  labels:
    app: kroki
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kroki
  template:
    metadata:
      labels:
        app: kroki
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - apache-demo
                topologyKey: kubernetes.io/hostname
      containers:
        - name: kroki
          image: yuzutech/kroki:0.26.0
          ports:
            - containerPort: 8000
      restartPolicy: Always
