---
apiVersion: v1
kind: LimitRange
metadata:
  name: resource-constraints
  namespace: kroki
spec:
  limits:
    - default: # default limits
        cpu: 250m
        memory: 256Mi
      defaultRequest: # default requests
        cpu: 001m
        memory: 64Mi
      max: # max and min define the limit range that a pod/container can specify (when outside, the pod will be rejected)
        cpu: 250m
        memory: 256Mi
      min:
        cpu: 001m
        memory: 64Mi
      type: Container
