---
apiVersion: v1
kind: Service
metadata:
  name: kroki-svc
  namespace: kroki
  labels:
    app: kroki
spec:
  selector:
    app: kroki
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30083
  type: NodePort
