---
apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: kroki
  namespace: kroki
  labels:
    app: kroki
spec:
  selector:
    app: kroki
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30083
  type: NodePort
