---
# see docs/api-docs/docker/monitoring-logging.md
services:
  prometheus:
    image: prom/prometheus:v3.0.1
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./assets/config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
      - /etc/timezone:/etc/timezone:ro
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - 9090:9090
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:9090/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 5

  grafana:
    image: grafana/grafana:11.4.0
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
    volumes:
      - ./assets/config/grafana:/etc/grafana/provisioning:ro
      - grafana_data:/var/lib/grafana
      - /etc/timezone:/etc/timezone:ro
    ports:
      - 3000:3000
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      prometheus:
        condition: service_healthy

  blackbox_exporter:
    image: prom/blackbox-exporter:v0.25.0
    container_name: blackbox_exporter
    restart: unless-stopped
    ports:
      - 9115:9115
    volumes:
      - ./assets/config/prometheus/blackbox-exporter.yml:/etc/prometheus/blackbox-exporter.yml:ro
      - /etc/timezone:/etc/timezone:ro
    command:
      - "--config.file=/etc/prometheus/blackbox-exporter.yml"
    depends_on:
      prometheus:
        condition: service_healthy

  reverse_proxy:
    image: nginx:1.24.0-bullseye
    container_name: reverse_proxy
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./assets/config/nginx:/etc/nginx/conf.d:ro
    privileged: true
    depends_on:
      grafana:
        condition: service_healthy

volumes:
  prometheus_data:
  grafana_data:
