---
services:

  pihole:
    image: pihole/pihole:2024.07.0
    container_name: pihole
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8100:80/tcp"
    environment:
      TZ: Europe/Berlin
      WEBPASSWORD: admin
      PIHOLE_DNS_: 8.8.8.8#53
      PROXY_LOCATION: &host admin-pi.fritz.box
      VIRTUAL_HOST: *host
    dns:
      - 127.0.0.1
      - 8.8.8.8
