---
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:2024.07.0
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "1080:80/tcp"
    environment:
      TZ: Europe/Berlin
      WEBPASSWORD: admin
    volumes:
      - ./target/etc-pihole:/etc/pihole
      - ./target/etc-dnsmasq.d:/etc/dnsmasq.d
    restart: unless-stopped
