---
# @file Portainer Compose Config
# @brief Docker stack for Portainer CE.
# @description
#   This `portainer` Docker stack starts a [Portainer CE](https://github.com/portainer/portainer)
#   instance. This [Portainer](https://docs.portainer.io) instance is pre-configured with an
#   admin user and handles deployments of other Docker stacks through GitOps techniques.
#
#   | Component | Port |URL                    |
#   | --------- | ---- |---------------------- |
#   | Portainer | 9990 | http://localhost:9990 |


services:

  portainer:
    image: portainer/portainer-ce:2.20.3-alpine
    container_name: portainer
    command: --host unix:///var/run/docker.sock --admin-password-file /tmp/portainer_passwords
    restart: always
    ports:
      - 9990:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
      - ./assets/portainer.passwd:/tmp/portainer_passwords
      - /etc/timezone:/etc/timezone:ro
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://localhost:9000 || exit 1"
      interval: 10s
      timeout: 10s
      retries: 6
      start_period: 10s

volumes:
  portainer_data:
