---
# - name: Minikube  ----  Install
#   ansible.builtin.include_tasks: 10-install.yml

# ! Remove Minikube binary before installing a new version
- name: Minikube  ----  Uninstall
  ansible.builtin.include_tasks: 90-uninstall.yml
