---
- name: Setup for group raspi
  hosts: raspi
  gather_facts: true
  become: true
  vars_files:
    - ../vars/global.yml
    - ../vars/raspi.yml
  tasks:

    - ansible.builtin.import_tasks: ../tasks/main/common-bash-aliases.yml
    - ansible.builtin.import_tasks: ../tasks/main/common-bash-prompt.yml
    - ansible.builtin.import_tasks: ../tasks/main/common-create-directories.yml
    - ansible.builtin.import_tasks: ../tasks/main/common-packages.yml
    - ansible.builtin.import_tasks: ../tasks/main/common-git.yml
    - ansible.builtin.import_tasks: ../tasks/main/common-ssh.yml
    - ansible.builtin.import_tasks: ../tasks/main/ubuntu-docker.yml

- name: Setup for group raspi (non-root)
  hosts: raspi
  gather_facts: true
  become: false
  vars_files:
    - ../vars/global.yml
    - ../vars/raspi.yml
  tasks:

    - ansible.builtin.import_tasks: ../tasks/main/common-atuin.yml
