---
- name: Import baseline playbook
  ansible.builtin.import_playbook: raspi-baseline.yml

- name: Setup for group raspi_talos
  hosts: raspi_talos
  gather_facts: true
  become: true
  vars_files:
    - ../vars/global.yml
    - ../vars/talos.yml
  tasks:

    - ansible.builtin.import_tasks: ../tasks/raspi-talos-mgmt.yml
    - ansible.builtin.import_tasks: ../tasks/raspi-talos-node-exporter.yml
    - ansible.builtin.import_tasks: ../tasks/raspi-talos-cluster-config.yml
