---
- name: Import baseline playbook
  ansible.builtin.import_playbook: raspi-baseline.yml

- name: Setup for group raspi_talos
  hosts: raspi_talos
  gather_facts: true
  become: true
  vars_files:
    - ../vars/global.yml
    - ../vars/talos.yml
  tasks:

    - ansible.builtin.import_tasks: ../tasks/raspi-talos-mgmt.yml
    - ansible.builtin.import_tasks: ../tasks/raspi-talos-node-exporter.yml

    # ! Only run this task once when the cluster is setup or re-installed from scratch.
    # ! Re-installing from scratch means that the SD cards have been flashed with a new image.
    # - ansible.builtin.import_tasks: ../tasks/raspi-talos-cluster-config.yml

- name: Setup for group raspi_talos (non-root)
  hosts: raspi_talos
  gather_facts: true
  tasks:

    # ! Must be last task in this play
    # ! Local changes result in a failure for this task
    # ! In case of failure, all other tasks for the affected node are skipped
    - ansible.builtin.import_tasks: ../tasks/raspi-talos-mgmt-clone-repos.yml
