---
- name: Setup for group raspi
  hosts: raspi
  gather_facts: true
  become: true
  vars_files:
    - ../vars/global.yml
    - ../vars/raspi.yml
  tasks:

    - ansible.builtin.import_tasks: ../tasks/common-bash-aliases.yml
    - ansible.builtin.import_tasks: ../tasks/common-bash-prompt.yml
    - ansible.builtin.import_tasks: ../tasks/common-create-directories.yml
    - ansible.builtin.import_tasks: ../tasks/common-packages.yml
    - ansible.builtin.import_tasks: ../tasks/common-git.yml
    - ansible.builtin.import_tasks: ../tasks/common-ssh.yml
    - ansible.builtin.import_tasks: ../tasks/ubuntu-docker.yml
