---
- name: Setup for group raspi
  hosts: raspi_talos
  gather_facts: true
  become: true
  vars_files:
    - ../vars/global.yml
  vars:
    ops_project_name: ops
    ops_compose_file: "/home/{{ ansible_user }}/work/repos/sommerfeld-io/configs-homelab/components/docker-stacks/ops/docker-compose.yml"
    portainer_project_name: portainer
    portainer_compose_file: "/home/{{ ansible_user }}/work/repos/sommerfeld-io/configs-homelab/components/docker-stacks/portainer/docker-compose.yml"
  tasks:

    - ansible.builtin.import_tasks: ../tasks/common-bash-prompt.yml
    - ansible.builtin.import_tasks: ../tasks/common-bash-aliases.yml
    - ansible.builtin.import_tasks: ../tasks/common-create-directories.yml
    - ansible.builtin.import_tasks: ../tasks/common-packages.yml
    - ansible.builtin.import_tasks: ../tasks/common-git.yml
    - ansible.builtin.import_tasks: ../tasks/common-ssh.yml
    - ansible.builtin.import_tasks: ../tasks/raspi-talos-mgmt.yml
    - ansible.builtin.import_tasks: ../tasks/raspi-talos-mgmt-node-exporter.yml
