---
- name: Install and configure nodes
  hosts: raspi
  gather_facts: true
  become: true
  vars_files:
    - ../vars/global.yml
    - ../vars/raspi.yml
  tasks:

    - ansible.builtin.include_tasks: ../roles/bash/tasks/main.yml
    - ansible.builtin.include_tasks: ../roles/filesystem/tasks/main.yml
    - ansible.builtin.include_tasks: ../tasks/common-packages.yml
    - ansible.builtin.include_tasks: ../tasks/common-task-setup.yml
    - ansible.builtin.include_tasks: ../tasks/common-task-config.yml
    - ansible.builtin.include_tasks: ../roles/git/tasks/main.yml
    - ansible.builtin.include_tasks: ../tasks/common-ssh.yml
    - ansible.builtin.include_tasks: ../tasks/ubuntu-docker.yml

- name: Install and configure nodes (non-root)
  hosts: raspi
  gather_facts: true
  become: false
  vars_files:
    - ../vars/global.yml
    - ../vars/raspi.yml
  tasks:

    - ansible.builtin.include_tasks: ../roles/atuin/tasks/main.yml

- name: Install and configure admin-pi specifics
  hosts: admin-pi.fritz.box
  gather_facts: true
  become: true
  vars_files:
    - ../vars/global.yml
    - ../vars/raspi.yml
  tasks:

    - ansible.builtin.include_tasks: ../roles/ansible/tasks/main.yml
