---
- name: Import baseline playbook
  ansible.builtin.import_playbook: raspi-baseline.yml

- name: Setup for group raspi_talos
  hosts: raspi_talos
  gather_facts: true
  become: true
  vars_files:
    - ../vars/global.yml
  tasks:

    - ansible.builtin.import_tasks: ../tasks/raspi-talos-mgmt.yml
    - ansible.builtin.import_tasks: ../tasks/raspi-talos-node-exporter.yml
    - ansible.builtin.import_tasks: ../tasks/raspi-talos-mgmt-k9s.yml
    - ansible.builtin.import_tasks: ../tasks/raspi-talos-mgmt-argocd-autopilot.yml

- name: Setup for group raspi_talos (non-root)
  hosts: raspi_talos
  gather_facts: true
  tasks:

    # ! Must be last task in this play
    # ! Local changes result in a failure for this task
    # ! In case of failure, all other tasks for the affected node are skipped
    - ansible.builtin.import_tasks: ../tasks/raspi-talos-mgmt-clone-repos.yml
