---
- name: Run telemetry stack (not the metrics) on dedicated host(s)
  hosts: admin-pi.fritz.box
  gather_facts: true
  become: false
  vars_files:
    - ../vars/global.yml
  tasks:

    - ansible.builtin.include_role:
        name: ../roles/telemetry
        tasks_from: monitoring-stack

    - ansible.builtin.include_role:
        name: ../roles/info
