---
- name: Run tests for group ubuntu_desktop
  hosts: ubuntu_desktop
  gather_facts: true
  become: false
  vars_files:
    - ../vars/tests.yml
  tasks:

    - ansible.builtin.import_tasks: ../tests/inspec.yml
