---
- name: Services  ----  Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: u=rwx,g=rx,o=rx
  with_items:
    - "{{ services_dot_repos_dir }}"
    - "{{ docker_stacks_dir }}"
