---
- name: Services  ---- Container Info  ----  Get container information
  community.docker.docker_host_info:
    containers: true
  register: services_docker_info

- name: "Services  ----  Container Info  ----  Display running containers"
  debug:
    msg: "container: {{ services_container.Names[0][1:] }} | Image: {{ services_container.Image }} | Status: {{ services_container.Status }}"
    verbosity: 0
  loop: "{{ services_docker_info.containers }}"
  loop_control:
    loop_var: services_container
    label: "{{ services_container.Names[0][1:] }}"
  when: services_docker_info.containers | length > 0
