---
- name: Services  ----  Info
  ansible.builtin.import_tasks: 10-info.yml

- name: Services  ----  Prepare directories
  ansible.builtin.import_tasks: 20-directories.yml

- name: Services  ----  Teardown
  ansible.builtin.import_tasks: admin-pi/telemetry/30-teardown.yml

- name: Services  ----  Clone
  ansible.builtin.import_tasks: admin-pi/telemetry/40-clone.yml

- name: Services  ----  Startup
  ansible.builtin.import_tasks: admin-pi/telemetry/50-startup.yml
