---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackbox-exporter
  namespace: telemetry
  labels:
    app.kubernetes.io/name: blackbox-exporter
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: blackbox-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: blackbox-exporter
    spec:
      containers:
        - name: blackbox-exporter
          image: prom/blackbox-exporter:v0.26.0
          ports:
            - name: http
              containerPort: 9115
          args:
            - "--config.file=/config/blackbox.yml"
          volumeMounts:
            - name: config-volume
              mountPath: /config
          resources:
            requests:
              cpu: "10m"
              memory: "16Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /probe
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /probe
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
      volumes:
        - name: config-volume
          configMap:
            name: blackbox-exporter-config

---
apiVersion: v1
kind: Service
metadata:
  name: blackbox-exporter
  namespace: telemetry
  labels:
    app.kubernetes.io/name: blackbox-exporter
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  selector:
    app.kubernetes.io/name: blackbox-exporter
  ports:
    - name: http
      port: 9115
      targetPort: http

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: blackbox-exporter-config
  namespace: telemetry
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  blackbox.yml: |
    modules:
      http_2xx:
        prober: http
        timeout: 5s
        http:
          valid_http_versions: ["HTTP/1.1", "HTTP/2"]
          valid_status_codes: [200]
          preferred_ip_protocol: "ip4"
      icmp:
        prober: icmp
        timeout: 5s
        icmp:
          preferred_ip_protocol: "ip4"

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: blackbox-exporter
  namespace: telemetry
  labels:
    release: kube-prometheus-stack
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: blackbox-exporter
  namespaceSelector:
    matchNames:
      - telemetry
  endpoints:
    - port: http
      interval: 30s

---
apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: blackbox-exporter-public-website-probe
  namespace: telemetry
  labels:
    release: kube-prometheus-stack
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  targets:
    staticConfig:
      targets:
        - https://www.sommerfeld.io
        - https://www.fb-brunnenbau.de
        - https://www.minifigs.de
  prober:
    url: blackbox-exporter.telemetry.svc.cluster.local:9115 # Adjust namespace if needed
  module: http_2xx
  interval: 30s
