---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: folder-overview
  namespace: telemetry
spec:
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  title: overview
