---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: folder-node-exporter
  namespace: telemetry
spec:
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  title: node-exporter
