---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: folder-kube-state-metrics
  namespace: telemetry
spec:
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  title: kube-state-metrics
