---
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    dashboards: "grafana"
  name: grafana
  namespace: telemetry
spec:
  config:
    log:
      mode: "console"
    security:
      admin_user: admin
      admin_password: admin
