---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: grafana
  name: grafana-nodeport-service
  namespace: telemetry
spec:
  ports:
    - name: grafana
      port: 3000
      protocol: TCP
      targetPort: grafana-http
      nodePort: 30000
  selector:
    app: grafana
  sessionAffinity: None
  type: NodePort
