---
# https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: talos-cluster
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 69.2.0
    helm:
      valuesObject:
        grafana:
          additionalDataSources:
            - name: Prometheus
              type: prometheus
              url: http://kube-prometheus-stack-prometheus:9090
          adminUser: admin
          adminPassword: admin
  destination:
    server: https://kubernetes.default.svc
    namespace: telemetry
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/name: grafana
  name: kube-prometheus-stack-grafana-nodeport
  namespace: telemetry
spec:
  ports:
    - name: http-web
      port: 80
      protocol: TCP
      targetPort: 3000
      nodePort: 30000
  selector:
    app.kubernetes.io/instance: kube-prometheus-stack
    app.kubernetes.io/name: grafana
  sessionAffinity: None
  type: NodePort
