---
# https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack
# https://www.infracloud.io/blogs/monitoring-endpoints-kubernetes-blackbox-exporter/
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: talos-cluster
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 70.3.0
    helm:
      valuesObject:
        grafana:
          enabled: false
        prometheus:
          enabled: true
          prometheusSpec:
            # storageSpec:
            #   volumeClaimTemplate:
            #     spec:
            #       accessModes: ["ReadWriteOnce"]
            #       resources:
            #         requests:
            #           storage: 2Gi
            additionalScrapeConfigs:
              - job_name: 'blackbox-public-websites'
                metrics_path: /probe
                params:
                  module: [http_2xx]
                static_configs:
                  - targets:
                      - https://www.sommerfeld.io
                relabel_configs:
                  - source_labels: [__address__]
                    target_label: __param_target
                  - source_labels: [__param_target]
                    target_label: instance
                  - target_label: __address__
                    replacement: prometheus-blackbox-exporter:9115
              - job_name: "blackbox-k8s-services"
                metrics_path: /probe
                params:
                  module: [http_2xx]
                kubernetes_sd_configs:
                  - role: service
                relabel_configs:
                  ## Example relabel to probe only some services that have "example.io/should_be_probed = true" annotation
                  # - source_labels: [__meta_kubernetes_service_annotation_example_io_should_be_probed]
                  #   action: keep
                  #   regex: true
                  - source_labels: [__address__]
                    target_label: __param_target
                  - target_label: __address__
                    replacement: prometheus-blackbox-exporter:9115
                  - source_labels: [__param_target]
                    target_label: instance
                  - action: labelmap
                    regex: __meta_kubernetes_service_label_(.+)
                  - source_labels: [__meta_kubernetes_namespace]
                    target_label: kubernetes_namespace
                  - source_labels: [__meta_kubernetes_service_name]
                    target_label: kubernetes_service_name

            retention: 30d
            requests:
              cpu: 100m
              memory: 256Mi
          additionalRulesForClusterRole:
            - apiGroups: [""]
              resources:
                - pods
                - services
              verbs: [ "get", "list", "watch" ]
  destination:
    server: https://kubernetes.default.svc
    namespace: telemetry
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
