---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-blackbox-exporter
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: talos-cluster
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus-blackbox-exporter
    targetRevision: 9.4.0
    helm:
      valuesObject:
        releaseLabel: true
        resources:
          limits:
            memory: 300Mi
            cpu: 200m
          requests:
            memory: 50Mi
            cpu: 50m
  destination:
    server: https://kubernetes.default.svc
    namespace: telemetry
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-blackbox-exporter-service-monitor
  namespace: telemetry
  labels:
    release: kube-prometheus-stack
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    ignore-check.kube-linter.io/dangling-servicemonitor: "Targeted labels for matchLabels selector are managed through the blackbox-exporter helm chart and already present"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: prometheus-blackbox-exporter
      app.kubernetes.io/name: prometheus-blackbox-exporter
      release: prometheus-blackbox-exporter
  namespaceSelector:
    matchNames:
      - telemetry
  endpoints:
    - port: http
      interval: 30s
      path: /probe
      params:
        module:
          - http_2xx
      relabelings:
        - sourceLabels: [__address__]
          targetLabel: __param_target
        - sourceLabels: [__param_target]
          targetLabel: instance
        - targetLabel: __address__
          replacement: prometheus-blackbox-exporter:9115
        - sourceLabels: [target_name]
          targetLabel: job
      staticConfigs:
        - labels:
            job: public-websites
          targets:
            - https://www.sommerfeld.io
            - https://www.minifigs.de
            - https://www.fb-brunnenbau.de
        - labels:
            job: talos-essentials
          targets:
            - http://grafana-nodeport-service.telemetry.svc.cluster.local
            - http://talos-cp.fritz.box:30000
        - labels:
            job: kroki
          targets:
            - http://kroki-svc.kroki.svc.cluster.local
            - http://talos-cp.fritz.box:30083
        - labels:
            job: talos-demos
          targets:
            - http://hello-world-nginx-helm-chart.hello-world-nginx.svc.cluster.local
            - http://talos-cp.fritz.box:32080
            - http://nginx-demo-svc.nginx-demo.svc.cluster.local
            - http://talos-cp.fritz.box:30081
            - http://apache-demo-svc.apache-demo.svc.cluster.local
            - http://talos-cp.fritz.box:30082
  jobLabel: job
