---
# https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: talos-cluster
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 70.3.0
    helm:
      valuesObject:
        grafana:
          enabled: false
          # adminUser: admin
          # adminPassword: admin
        prometheus:
          enabled: true
          additionalRulesForClusterRole:
            - apiGroups: [""]
              resources:
                - pods
                - services
              verbs: [ "get", "list", "watch" ]
  destination:
    server: https://kubernetes.default.svc
    namespace: telemetry
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
