---
# https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: prometheus-operator
  namespace: argocd
spec:
  project: talos-cluster
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 69.2.0
    helm:
      valuesObject:
        namespaceOverride: &namespace telemetry
        grafana:
          namespaceOverride: *namespace
          adminUser: admin
          adminPassword: admin
        kube-state-metrics:
          namespaceOverride: *namespace
        prometheus-node-exporter:
          namespaceOverride: *namespace
  destination:
    server: https://kubernetes.default.svc
    namespace: *namespace
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
