---
# https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-blackbox-exporter
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-blackbox-exporter
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: talos-cluster
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus-blackbox-exporter
    targetRevision: 9.4.0
    helm:
      valuesObject:
        releaseLabel: true
        resources:
          limits:
            memory: 300Mi
            cpu: 200m
          requests:
            memory: 50Mi
            cpu: 50m
  destination:
    server: https://kubernetes.default.svc
    namespace: telemetry
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
