---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: service-monitor-argocd-metrics
  namespace: argocd
  labels:
    release: kube-prometheus-stack
  annotations:
    ignore-check.kube-linter.io/dangling-servicemonitor: "ArgoCD automatically exposes services for metrics"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-metrics
  endpoints:
    - port: metrics
      interval: 5s

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: service-monitor-argocd-server-metrics
  namespace: argocd
  labels:
    release: kube-prometheus-stack
  annotations:
    ignore-check.kube-linter.io/dangling-servicemonitor: "ArgoCD automatically exposes services for metrics"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-server-metrics
  namespaceSelector:
    matchNames:
      - argocd
  endpoints:
    - port: metrics
      interval: 5s

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: service-monitor-argocd-repo-server-metrics
  namespace: argocd
  labels:
    release: kube-prometheus-stack
  annotations:
    ignore-check.kube-linter.io/dangling-servicemonitor: "ArgoCD automatically exposes services for metrics"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-repo-server
  namespaceSelector:
    matchNames:
      - argocd
  endpoints:
    - port: metrics
      interval: 5s

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: service-monitor-argocd-applicationset-controller-metrics
  namespace: argocd
  labels:
    release: kube-prometheus-stack
  annotations:
    ignore-check.kube-linter.io/dangling-servicemonitor: "ArgoCD automatically exposes services for metrics"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-applicationset-controller
  namespaceSelector:
    matchNames:
      - argocd
  endpoints:
    - port: metrics
      interval: 5s

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: service-monitor-argocd-dex-server
  namespace: argocd
  labels:
    release: kube-prometheus-stack
  annotations:
    ignore-check.kube-linter.io/dangling-servicemonitor: "ArgoCD automatically exposes services for metrics"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-dex-server
  namespaceSelector:
    matchNames:
      - argocd
  endpoints:
    - port: metrics
      interval: 5s

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: service-monitor-argocd-redis-haproxy-metrics
  namespace: argocd
  labels:
    release: kube-prometheus-stack
  annotations:
    ignore-check.kube-linter.io/dangling-servicemonitor: "ArgoCD automatically exposes services for metrics"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-redis-ha-haproxy
  namespaceSelector:
    matchNames:
      - argocd
  endpoints:
    - port: http-exporter-port
      interval: 5s

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: service-monitor-argocd-notifications-controller
  namespace: argocd
  labels:
    release: kube-prometheus-stack
  annotations:
    ignore-check.kube-linter.io/dangling-servicemonitor: "ArgoCD automatically exposes services for metrics"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-notifications-controller-metrics
  namespaceSelector:
    matchNames:
      - argocd
  endpoints:
    - port: metrics
      interval: 5s
