---
- name: Info  ----  Docker  ----  Get container information
  community.docker.docker_host_info:
    containers: true
  register: docker_info

- name: "Info  ----  Docker  ----  Display container information"
  debug:
    msg: "Container: {{ container.Names[0][1:] }} | Image: {{ container.Image }} | Status: {{ container.Status }}"
    verbosity: 0
  loop: "{{ docker_info.containers }}"
  loop_control:
    loop_var: container
    label: "{{ container.Names[0][1:] }}"
  when: docker_info.containers | length > 0
