---
name: 'Housekeeping: Issues in Project'

on:
  issues:
    types:
      - labeled
      - unlabeled

jobs:
  housekeeping-project:
    uses: sommerfeld-io/.github/.github/workflows/housekeeping-project.yml@main
    permissions:
      contents: read
      issues: read
      repository-projects: write
