---
name: "Provision: Grafana Cloud"

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/ansible-grafana-cloud.yml
      - ansible/playbooks/grafana-cloud.yml
      - ansible/roles/grafana-cloud/**
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:

  metrics-start-time:
    runs-on: ubuntu-latest
    outputs:
      start: ${{ steps.record-start.outputs.start }}
    steps:
      - uses: actions/checkout@v4
      - name: Record workflow start time
        id: record-start
        uses: ./.github/actions/record-workflow-start-time

  playbook:
    runs-on: ubuntu-latest
    needs: [metrics-start-time]
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          submodules: true
      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible
          ansible-galaxy collection install community.grafana grafana.grafana
          pipx inject ansible-core requests
        shell: bash
      - name: Show versions
        run: |
          ansible --version
          ansible-galaxy collection list | grep -Ei 'community.grafana|grafana.grafana'
        shell: bash
      - name: Run playbook
        env:
          PLAYBOOK: grafana-cloud.yml
          VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
        run: |
          git submodule update --remote
          (
            cd ansible || exit
            echo "$VAULT_PASSWORD" > vault.pass
            ansible-playbook "playbooks/$PLAYBOOK" --inventory hosts.yml --vault-password-file vault.pass
          )
        shell: bash

  metrics-to-grafana-cloud:
    runs-on: ubuntu-latest
    needs: [metrics-start-time, playbook]
    if: always()
    steps:
      - uses: actions/checkout@v4
      - name: Push workflow metrics to Grafana Cloud
        uses: ./.github/actions/push-workflow-metrics
        with:
          job_results: >-
            {
              "playbook": "${{ needs.playbook.result }}"
            }
          start_time: ${{ needs.metrics-start-time.outputs.start }}
          metrics_user: ${{ secrets.GRAFANA_CLOUD_USER }}
          metrics_token: ${{ secrets.GRAFANA_CLOUD_TOKEN }}
          metrics_url: ${{ secrets.GRAFANA_CLOUD_URL }}
