---
global:
  scrape_interval: 5s
  external_labels:
    monitor: prometheus-grafana-stack
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090
  ##############################################################################
  #    node exporter                                                           #
  ##############################################################################
  - job_name: node-metrics
    scrape_interval: 5s
    static_configs:
      - targets:
          - caprica.fritz.box:9100
          - kobol.fritz.box:9100
          - admin-pi.fritz.box:9100
        labels:
          group: node-metrics
      - targets:
          - caprica.fritz.box:9110
          - kobol.fritz.box:9110
        labels:
          group: docker-metrics
  - job_name: talos-cluster-metrics
    scrape_interval: 5s
    static_configs:
      - targets:
          - talos-cp.fritz.box:30091
          - talos-w1.fritz.box:30091
          - talos-w2.fritz.box:30091
          - talos-w3.fritz.box:30091
        labels:
          group: node-metrics
  ##############################################################################
  #    blackbox exporter                                                       #
  ##############################################################################
  - job_name: homelab-services
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
          - kobol.fritz.box:9990
          - caprica.fritz.box:9990
          - admin-pi.fritz.box:9990
          - talos-cp.fritz.box:30081
          - talos-cp.fritz.box:30082
          - talos-cp.fritz.box:30083
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115
  - job_name: monitoring-logging
    metrics_path: /probe
    params:
      module: [http_2xx] # Look for a HTTP 200 response.
    static_configs:
      - targets:
          - admin-pi.fritz.box:80
          - admin-pi.fritz.box:3000
          - admin-pi.fritz.box:9090
          - talos-cp.fritz.box:30001
          - talos-cp.fritz.box:30002
          - talos-cp.fritz.box:30092
          - talos-cp.fritz.box:30093
          - talos-cp.fritz.box:30094
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115
  - job_name: websites
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - www.sommerfeld.io
          - www.fb-brunnenbau.de
          - www.minifigs.de
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115
  ##############################################################################
  #    ArgoCD metrics                                                          #
  ##############################################################################
  - job_name: argocd-metrics
    static_configs:
      - targets:
          - talos-cp.fritz.box:30092
          - talos-cp.fritz.box:30093
          - talos-cp.fritz.box:30094
        labels:
          instance: argocd
  ##############################################################################
  #    Kubernetes metrics                                                      #
  ##############################################################################
  - job_name: kube-state-metrics
    static_configs:
      - targets:
          - talos-cp.fritz.box:30090
        labels:
          instance: argocd
